### ISSUE TITLE
SRI: Comments on *Is resource eligible for integrity validation*, 3.3.2

### ISSUE THREAD

**Issue by mozfreddyb** [w3c/webappsec#105]
I discussed this with @fmarier and we had a few concerns:

> 4. If the origin of request is resource’s origin, return true.

This is a bit confusing, even with the link to fetch at "origin of request". The fetch spec part that is linked says the request origin is "an opaque identifier" unless stated otherwise and I am entirely sure it is not an opaque identifier in almost all interesting cases of SRI, but rather the documents effective scripting origin. How would we translate this into understandable spec text?

--

> 3. If the mode of request is CORS, return true

For `script` tags, the mode of request is not CORS, but we *do* want to check if the resource is CORS-enabled or same-origin.
Does this just mean we have to look into the `Access-Control-Allow-Origin` header?
I guess, we can not set the request-mode for existing tags to something else (i.e. monkeypatch HTML). But we do have to make sure that the *effective script origin* of the current document (or just the *script origin*?!) is allowed to read the resources, before we continue.

I'd especially like more comments on this one!

**Comment by devd** [comment]
doesn't adding a crossorigin=anonymous solve this concern?

**Comment by mozfreddyb** [comment]
I just learned how the crossorigin=anonymous attribute works. Sounds like a perfect fit :+1: 
Let's discuss details in #190 :)
