### ISSUE TITLE
[SRI] Inconsistent Integrity Metadata Conventions

### ISSUE THREAD

**Issue by lgarron** [w3c/webappsec#114]
I tried testing SRI in Chrome by following the [Integrity Metadata](https://github.com/w3c/webappsec/blob/5be9cb4b92642b3789dae3c238c70ff6ea11a2e2/specs/subresourceintegrity/spec.markdown#integrity-metadata) section. It appears to match RFC6920, but I had to make the following changes to get it to work:

- Change `sha-256` to `sha256`
- Remove the first two replacements from `sed` in the example command (i.e. use the base 64 output from OpenSSL with the `=` signs removed and no other changes).

It might just be something we need to fix in Chrome, but Joel encouraged me file an issue to make sure that all the specs and implementations match at some point.

**Comment by mozfreddyb** [comment]
We discussed this in https://github.com/w3c/webappsec/pull/125 already. Let's keep it in one place, please.
