### ISSUE TITLE
Explicitly mention the four cases around the HTTPS requirement in SRI

### ISSUE THREAD

**Issue by fmarier** [w3c/webappsec#116]
In terms of requiring secure origins or not, there are four cases:

1. http page loading an http resource
2. http page loading an https resource
3. https page loading an http resource (should be blocked by mixed content)
4. https page loading an https resource (not controversial, of course)

Whether or not we should allow the first two to have integrity attributes is still being discussed (for example [on the chromium security-dev list](https://groups.google.com/a/chromium.org/d/topic/security-dev/hJwYZOOPaH4/discussion)).

We should address these explicitly in the spec and tell implementers:
- whether they are allowed to ignore the integrity attribute in any of these cases
- whether they are allowed to block the sub-resource if it contains an integrity attribute

**Comment by fmarier** [comment]
Actually, if we change at least one of the examples (as I've done in #181), it should be clear that SRI is orthogonal to TLS.

**Comment by devd** [comment]
I am a bit uncomfortable doing that because I think (in 2015) all specs
should only use ssl in all their examples. But maybe thats just me?

**Comment by metromoxie** [comment]
I'm with @devd. We should stick with HTTPS in our examples because that's how you should be writing code; everything else is a hack for backwards compatibility, as far as I'm concerned (okay, maybe that's a little harsh).

**Comment by fmarier** [comment]
In that case, we'll need to write something about how user agents must honor the integrity attribute on both HTTP and HTTPS.

**Comment by metromoxie** [comment]
Agreed. I'm happy to take this on and write up a pull request.

**Comment by mozfreddyb** [comment]
Fixed by @metromoxie via #204 and #213.
