### ISSUE TITLE
Resolve ambiguity in the "parse metadata" algorithm between "()" and "no metadata"

### ISSUE THREAD

**Issue by fmarier** [w3c/webappsec#119]
The "parse metadata" algorithm in the spec currently return one of three things:
1. "no metadata"
2. an empty set
3. a non-empty set of integrity metadata

In #86, I argued that cases 1 and 2 should be the same and removed that distinction. There are two consequences to that change (or clarification):

- If a user agent sees a hash algorithm it doesn't support (e.g. `md5` or `sha-3000`), then it will ignore the integrity check and load the script, as per 3.3 of the parse metadata algorithm.
- If a user agent sees an integrity metadata with another scheme than `ni` (e.g. `bogus:///sha-256...`), then  it will ignore the integrity check and load the script, as per 3.1 of the parse metadata algorithm.

Is what I'm describing the intended behavior or do we intend to block both of these cases?

@mastahyeti uses the latter interpretation in his [SRI test page](https://btoews.github.io/sri_test/).

**Comment by fmarier** [comment]
In order to clarify the path forward, let's look at these test cases:

1. `integrity=""`
2. `integrity="sha3-lpWCelt2QAg3wZScVGlb/93I9Ivsfb0VG/p+SPmxJFE="`
3. `integrity="garbage"`

The first case is not controversial and has never been blocked. The second case was [discussed on the list](https://lists.w3.org/Archives/Public/public-webappsec/2014Dec/0242.html) and it sounds like we [have agreed](http://www.w3.org/2011/webappsec/draft-minutes/2015-02-23-webappsec-minutes.html#item07) to allow it to load.

The question is what to do with the third case. If we want to filter out anything that's invalid or not recognized and allow the load to proceed as if the integrity attribute were empty, then we can merge #86.

Otherwise, I need to prepare a new PR for the algorithm that will look like:

1. parse the integrity attribute
2. remove any valid-looking metadata with unsupported hash types
3. trim the string
4. if the integrity attribute is now empty, ignore it and load the resource
5. if it's not empty, look for a valid metadata and use it to verify the load
6. if no valid metadata is found, abort the load

**Comment by fmarier** [comment]
I should point out that from an implementation point of view, treating all three test cases as empty is much easier.

If we don't go that way, then we have to decide:

* how garbage differs from an unknown but well-formed hash (the presence of a hyphen in the string?)
* how garbage differs from an unknown but well-formed option (the presence of a semicolon in the string?)

**Comment by devd** [comment]
My vote is for treating as all three cases as empty for the purposes of the
algorithm; individual UAs should decide how they want to treat each case
for DEV tools and warnings

**Comment by mozfreddyb** [comment]
I agree. Would it make sense to add an informal note that UAs *may* want to warn about incorrect integrity metadata?

**Comment by fmarier** [comment]
> Would it make sense to add an informal note that UAs may want to warn about incorrect integrity metadata?

I'm not sure if we need to have that in the spec, but it's in my implementation as a devtools warning.
