### ISSUE TITLE
Should we get sha-384 and sha-512 added to the named information IANA registry?

### ISSUE THREAD

**Issue by fmarier** [w3c/webappsec#121]
We use RFC6920 URIs in the SRI spec to encode the hash algorithm and value. That RFC [created](http://tools.ietf.org/html/rfc6920#section-9.4) a new [registry](https://www.iana.org/assignments/named-information/named-information.xhtml#hash-alg) for the approved hash algorithms.

Since we intend to support `sha-512` (and potentially `sha-384` to match the [CSP spec](http://www.w3.org/TR/CSP2/#source-list-valid-hashes)), should we get these algorithms added to the registry? Or is the right process to do that after we publish the spec?

**Comment by devd** [comment]
I don't really know. ask on the list? (closing since there isn't really a patch to the spec we need to do)

**Comment by fmarier** [comment]
Moved to the list: http://lists.w3.org/Archives/Public/public-webappsec/2015Jan/0017.html
