### ISSUE TITLE
[SRI] Typo: missing hyphen in 3.10.1: ni:///sha-256

### ISSUE THREAD

**Issue by manger** [w3c/webappsec#133]
A hyphen is missing from the integrity ni URI in the note in section 3.10.1 "The a element":

WRONG:
  integrity="ni:///sha256;…
RIGHT:
  integrity="ni:///sha-256;…

**Comment by fmarier** [comment]
This was fixed in b4f4c76c7cf64fc5550d6ab148b1697d8c1dbdbe.
