### ISSUE TITLE
SRI: Consider converting to Bikeshed.

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec#141]
Bikeshed does nice things with definitions and autolinking (and every other WebAppSec spec uses it at the moment); it might be a good idea to convert SRI to that framework rather than the hacked-up respec+Make thing I put together originally.

WDYT, @devd, @mozfreddyb, @fmarier, and @metromoxie?

**Comment by mozfreddyb** [comment]
This is the first time I heard of [Bikeshed](https://github.com/tabatkins/bikeshed/) and I'm a bit hesitant as I don't fully understand what this would entail :)

I'm not super happy with the mix of HTML+Markdown that we now have, but I kinda know my way around things. I'm a bit afraid that a change would stall progress, which I'd rather have after v1 than before.

I skimmed the docs (mostly Installing and Quickstart), but still couldn't figure the whole workflow out entirely.

**Comment by mozfreddyb** [comment]
> I suggest we switch after v1, if at all.

after v1 LC has ended or so..

**Comment by mikewest** [comment]
Look at any of the other specs; you'll see an `index.src.html` and an `index.html`. The latter is generated from the former via `bikeshed -f spec path/to/source/file`. Not much more to it than that.

But sure, there's no particular rush. You're doing most of the editing at the moment, so I'm certainly not going to force it on you, but I do find it to be a significantly better tool in a number of ways (mostly regarding autolinking).

**Comment by metromoxie** [comment]
Hm, Bikeshed does look nice, so I wouldn't object to the conversion, but as @mozfreddyb said, I, too, would be afraid that change would stall progress.

**Comment by devd** [comment]
Is this the issue with the max number of editors commenting? Are we literally bike shedding ? :P

**Comment by metromoxie** [comment]
I hereby propose that, post CR, we go ahead and convert to Bikeshed. I've played around enough with it to love it and vastly prefer it to our current, ad-hoc setup. I also agree to be the sucker that does it, so I'm assigning this to myself, as long as y'all approve of it.

**Comment by mozfreddyb** [comment]
sure, that works for me.

**Comment by mozfreddyb** [comment]
See https://github.com/w3c/webappsec/pull/459#issuecomment-144759314 about auto-publishing to w3.org :/

**Comment by metromoxie** [comment]
I have faith in @tabatkins. Given that we don't need to do this conversion soon (esp since I won't do it until at least after CR, and probably until even full publication), I suspect Bikeshed will be fixed up by then to handle this. That, or I'll harass @tabatkins until it is :-)

**Comment by tabatkins** [comment]
Dunno what plh is on about there. Figuring out what's up.

**Comment by metromoxie** [comment]
Tracking this in the new SRI repo: w3c/webappsec-subresource-integrity#12
