### ISSUE TITLE
[SRI] Add a note about falling back to another resource if the integrity check fails

### ISSUE THREAD

**Issue by fmarier** [w3c/webappsec#149]
As mentioned by @devd on https://github.com/w3c/webappsec/pull/118#issuecomment-70456839, web developers should probably check for any integrity failures and fallback to a known good resource. We should probably add something to that effect in the spec.

**Comment by mozfreddyb** [comment]
:+1:

**Comment by fmarier** [comment]
Note that the `onerror` callback will only be invoked in the case of same-origin sub-resources (see the section on "Cross-origin data leakage" at the end of the spec).

The "failed load" detection logic will therefore be slightly more complicated.

**Comment by mozfreddyb** [comment]
Yes, if you use a CDN for e.g. jQuery you'd have to write a script that checks if jQuery is undefined and dynamically add a new `<script>`.

Wow this sounds painful for developers :/

**Comment by devd** [comment]
why not invoke the onerror callback for a successful cors load?

**Comment by fmarier** [comment]
@devd good point. we should probably add that to the spec (the section that talks about modifications to the fetch spec)

**Comment by devd** [comment]
hmm I thought the bit about "If resource is same origin with the origin of the link element's Document, then queue a task to fire a simple event named error at the link element." is where I would modify the text?

**Comment by fmarier** [comment]
Sorry, yeah, that's what I was thinking of too, not the Fetch part.

https://w3c.github.io/webappsec/specs/subresourceintegrity/#elements-1

**Comment by devd** [comment]
@annevk do you have thoughts on how to phrase the wording and algorithm to say:

1. If it is a CORS fetch, and it is a CORS error, throw the CORS error.
2. If it is a CORS Fetch and CORS check succeeded but hash didn't match, throw error similar to same origin error.

**Comment by fmarier** [comment]
Note: from an implementation (in Firefox) point of view, I don't have to worry about throwing a CORS error since these resources will be blocked earlier (with the appropriate error) and will never reach the SRI code.

**Comment by devd** [comment]
yup.. but do you throw an error event if there CORs is ok?

**Comment by fmarier** [comment]
Not currently, I only throw an error when the sub-resource is sameorigin with the page.

**Comment by annevk** [comment]
It's a bit unclear what you guys are discussing. Presumably you need to patch "Fetch" in order for this new feature to work at all, no? So CORS would then happen automatically.

**Comment by metromoxie** [comment]
I actually have concerns about the spec here as well. I think it's actually inconsistent with CSP behavior. In CSP, if we block a script b/c it isn't in the script-src, I believe the onload event is stilled fired (but a separate SecurityPolicyViolationEvent occurs). Similarly, I feel like the right answer here might be to led the load happen, but just not execute the script.

Also, Chrome has a similar implementation to what @fmarier described. We get the CORS error for free because the code never reaches SRI. However, for us, rejecting the SRI before the load event has fired is tough (at least in the style case).

**Comment by annevk** [comment]
That makes little sense to me. If CSP failure is defined as "network error" it should behave as such, no? It sounds like the layering is a bit off.

**Comment by mikewest** [comment]
We should fire the error event, just like we would if someone pulled the network cable during the fetch. This will be clearer in CSP once I get off my lazy butt and rewrite CSP in terms of Fetch, but it should already be clear in SRI, since I did write it in terms of Fetch (didn't I?).

**Comment by mikewest** [comment]
I apparently didn't. :(

I'd suggest rewriting the https://w3c.github.io/webappsec/specs/subresourceintegrity/#modifications-to-fetch section of SRI to just drop the request on the floor if we end up with a corrup response.

**Comment by devd** [comment]
by drop the request on the floor, you mean the normal network error? If so, yes I agree. We should have a flag in there to let JS know that it is a SRI error/corrupt response.

**Comment by annevk** [comment]
I think for v1 leaving that up to developer tools is fine.

**Comment by devd** [comment]
Leaving what up to the developer tools?

**Comment by annevk** [comment]
What the cause of the network error was. There's no granularity in that now (mostly because we decided that would be bad for security), adding it for SRI feels premature (although I don't think adding it would be bad for security).

**Comment by devd** [comment]
I think we can throw a generic network error with a flag or create violation events like CSP. In the end, the security concerns are the same and I don't see what creating new types of events buys us.

**Comment by metromoxie** [comment]
Agreed. Let's just throw a network error. Seems simplest to me.

**Comment by fmarier** [comment]
I'm good with a simple network error too. I assume we continue to trigger the error only when the page and the sub-resource share the same origin?

**Comment by devd** [comment]
Or on a valid cors response.

How do authors detect it is a SRI error?

**Comment by annevk** [comment]
They don't (perhaps through the developer console they could). Just like they can't distinguish CORS from DNS errors.

**Comment by devd** [comment]
hmm .. do you know the history behind that decision? It seems really sucky to not be able to detect CORS errors (to tell your CDN to set the right flags)?

**Comment by annevk** [comment]
We don't want to give attackers more information about stuff protected by SOP.

**Comment by annevk** [comment]
E.g. if you get a CORS error you know you've found an endpoint that talks HTTP.

**Comment by devd** [comment]
Hmm..I a dubious of whether that is worth the impact on usability, but
never mind. We can still do network error and SRI error separately. Cors
error is network error.

**Comment by fmarier** [comment]
Is it worth having two different error types?

It seems to me like in both cases (network error, SRI error), what the site needs to do is: load the resource locally and then investigate why the CDN is broken.

**Comment by annevk** [comment]
Agreed. Developer tools can reveal more information, but there's no need to jump the gun on remote debugging here.

**Comment by devd** [comment]
hmm .. maybe I am too worried about impact on adoption. Since I haven't played with SRI deployment, I will defer to @josh @mastahyeti @oreoshake wdyt of not having any events or reporting for SRI deployment? Will it be a huge negative?

Alternatively, @fmarier @metromoxie would it make sense that SRI not enforce if the fetch has been overridden by a locally installed SSL cert?

**Comment by fmarier** [comment]
Just to be clear, I think that the proposal is to trigger `onerror` on the `<script>` element when the integrity check fails.

**Comment by mikewest** [comment]
One risk we wanted to mitigate was the ability to read data cross-origin, using SRI as an oracle. I would suggest that y'all should avoid locking yourselves into distinguishing SRI failures from other failures for that reason.

If you do choose to have an SRI-specific error, it would be good to ensure that MIME-type and CORS checks happen before integrity validation, to avoid leaking data in unintended cases.

**Comment by annevk** [comment]
Yeah, if CORS is okay you can avoid the SRI-oracle, but I'm still skeptical that remote debugging is a necessary v1 feature.

**Comment by devd** [comment]
Sorry -- I meant, that onerror won't tell me it is a SRI issue; it will be indistinguishable from a network error.
@mikewest the spec in its current mode requires CORS to be ok. We can say that "allow the distinguished SRI error if CORS is ok" just so that we can allow future caching benefits.

**Comment by metromoxie** [comment]
I really lean towards treat it as a network error. As @annevk says, why worry about remote debugging in v1, unless I'm missing some other use? I'm pretty worried about getting oracle issues correct.

**Comment by fmarier** [comment]
So it sounds like the note we need to add (the original purpose of this bug) is something like:

> Authors wanting to fallback to another resource when the integrity check fails should register an error callback on the resource and write a JavaScript error handler which replaces the resource with a different one.

**Comment by devd** [comment]
ok sgtm

**Comment by metromoxie** [comment]
+1

**Comment by mozfreddyb** [comment]
yes! :)

**Comment by metromoxie** [comment]
Please double check my pull request in particular for:
* The correct location of the note. I felt that it made sense to add it to the "Handling integrity violations" section, since that will be a likely place for a developer to look to see "what to do."
* My wording and especially whether we should add a note about considering a "noncanonical-src" attribute. I lean against it, b/c why commit ourselves, but it might be useful to know that it's under consideration.

**Comment by mozfreddyb** [comment]
I think this is well placed. On top, we should add an example to 1.2 that implements a basic failover and mentions our plans to provide some sort of fallback attribute.

**Comment by metromoxie** [comment]
@mozfreddyb, I'm not sure of a good way to write in an example of how to do this; it seems like a pretty specific, non-normative thing to be giving an example of. If you feel like you have a good way of presenting it, though, feel free to write up an example.

**Comment by mozfreddyb** [comment]
@metromoxie The good thing about chapter 1 is that everything in there is marked non-normative. I was just going to go ahead and do the simple `addEventListener` thing.
To recover from a failed integrity check seemed like a common use case to me, but I'm OK with leaving it out if you guys think it is too specific.

**Comment by fmarier** [comment]
I think what we have is sufficient. Web authors who care should be able to figure out how to catch the error and pull in a different script.
