### ISSUE TITLE
[MIX] HSTS and Resource Fetching

### ISSUE THREAD

**Issue by ylafon** [w3c/webappsec#157]
Hi,
Section 4.1 talks in a Note about HSTS forcing all content in the 'blockable' category, which is related to [HSTS Ancillary Requirement](https://tools.ietf.org/html/rfc6797#section-2.4.1.2) number 1, but nothing in section 4.1 or in anywhere else (thinking of section 5) about [HSTS Core Requirements](https://tools.ietf.org/html/rfc6797#section-2.4.1.1) number 4, URI scheme rewriting (See also [HSTS URI Loading and Port Mapping](https://tools.ietf.org/html/rfc6797#section-8.3) ). 
There are a few issues here:
Is the characterization of the potentially secure/a priori insecure URLs done before or after applying HSTS URL rewriting? The same question goes if the request is handled by a ServiceWorker (and in fact anything that is impacting resource fetching).

**Comment by mikewest** [comment]
Hi! It's probably reasonable to bring questions like this to public-webappsec@, as I think only a few of the editors really follow GitHub issues (I know I'm usually pretty slow at seeing GitHub notifications...).

With that in mind, HSTS is a good question! At the moment:

1. HSTS happens after mixed content checking. We've had a number of threads on this, and there are reasonable arguments on both sides, but this is, I think, where we've come down pretty solidly. https://lists.w3.org/Archives/Public/public-webappsec/2014Nov/0306.html and related is the most recent, most relevant thread.

2. Service workers happen after an initial round of mixed content checking. That is, we see a request for X, we evaluate it against mixed content checking at the top of Fetch, and then, if it passes, it moves into the service worker for processing (where it will again be subject to mixed content checks).

**Comment by ylafon** [comment]
Ok, I'm sending something to public-webappsec ML.

**Comment by mikewest** [comment]
Great! I'll leave this open until the thread resolves, just in case we need to make changes to the spec.

**Comment by mikewest** [comment]
We didn't make any changes to MIX, closing this out.

That said, this discussion is tangentially happening again in the context of the UPGRADE spec. Let's see if it goes anywhere there before making spec changes.
