### ISSUE TITLE
[POWER] should provide a single agorithm that checks both the Document and Settings Object

### ISSUE THREAD

**Issue by jyasskin** [w3c/webappsec#160]
https://w3c.github.io/webappsec/specs/powerfulfeatures/#new recommends that each spec include a 4-step algorithm to check the Document's security if a document is present, and then to fall back to checking the settings object. This seems like a recipe for errors in other specs. It's even causing problems in [POWER] where the [geolocation example](https://w3c.github.io/webappsec/specs/powerfulfeatures/#legacy-example) only checks the settings object and not the document.

I'd suggest that either [Is settings object a sufficiently secure context?](https://w3c.github.io/webappsec/specs/powerfulfeatures/#settings-sufficiently-secure) should check its responsible document on its own, or we should add a third algorithm and a note about when one would want to check only the settings object.

**Comment by mikewest** [comment]
Yes. The boilerplate is terrible, and there's no reason to make anyone other than me write it. I was thinking that while writing the example, but blew it off.

Thanks for bringing it up. I'll try to poke at the text tomorrow.

**Comment by mikewest** [comment]
Took a stab at this. Mind skimming the text to see if it's sane?

**Comment by jyasskin** [comment]
I added some comments on the change, and asked on the mailing list whether wording like ["If the incumbent settings object is not a sufficiently secure context, reject promise with a SecurityError and abort these steps."](https://webbluetoothcg.github.io/web-bluetooth/#requestDevice-secure-context) is a reasonable thing to use.

**Comment by mikewest** [comment]
Works for me, thanks for the feedback! I expanded a bit on the "sufficiently secure context" definition to make sure you're covered with that text, and changed the example accordingly.
