### ISSUE TITLE
[SRI] Add support for the base64 encoding

### ISSUE THREAD

**Issue by fmarier** [w3c/webappsec#163]
We currently require the base64url encoding, but I believe both implementations currently do:

1. take user's base64url encoding and convert it to base64 by replacing "-" and "_" with "+" and "/"
2. decode the base64 blob to binary

Which means that if the user's encoding was already base64 (and not base64url) then it will work just fine.

Should we:

1. build that flexibility into the spec, or
2. pick base64 only and simplify the code/spec

CSP Level 2 used to be base64 only but has just [added base64url](https://github.com/w3c/webappsec/pull/154) as an option [to match the SRI spec](https://github.com/w3c/webappsec/pull/156#issuecomment-72209356).

**Comment by devd** [comment]
I am a fan of 1.

**Comment by fmarier** [comment]
CSP2 has just [removed base64url](https://github.com/w3c/webappsec/pull/171) from the spec, as per https://lists.w3.org/Archives/Public/public-webappsec/2015Feb/0153.html.

**Comment by devd** [comment]
sgtm ; lets just do 2 then.

**Comment by mozfreddyb** [comment]
Let's use base64 only then :)

**Comment by fmarier** [comment]
Option 2 (base64 only) was done as part of #156.
