### ISSUE TITLE
[CSPP] how are multiple max-age directives handled?

### ISSUE THREAD

**Issue by dveditz** [w3c/webappsec#164]
In a Content-Security-Policy-Pin header how are multiple max-age directives handled? There are several plausible choices:
 * reject header as malformed
 * take the first or last
 * use the largest
 * use the shortest, or assume an unset attempt
 * split the difference and use the average of the max-age values

I'd prefer using the largest since the site can easily fix it on the next connection. I dislike the arbitrariness of the order dependent options and rejecting the policy isn't helpful or safe for the site.

**Comment by mikewest** [comment]
According to https://tools.ietf.org/html/rfc6797#section-6.1, HSTS will ignore a malformed header (which would include one that repeated directives). That seems a bit draconian in this case.

I don't really have a strong preference. If you prefer using the largest value, then so be it.
