### ISSUE TITLE
CREDENTIAL: opaque FormData link leads outside of W3C specs

### ISSUE THREAD

**Issue by jmajnert** [w3c/webappsec#199]
In the Credential Management document, the opaque FormData definition leads to a document that is not outside of W3C repo: http://mikewest.github.io/credentialmanagement/writeonly/#opaque-formdata

What is the plan regarding this definition?

**Comment by mikewest** [comment]
It's a good question. One proposal is to reverse the API such that the FormData object isn't necessary. If we go that route, wonderful. If not, we'll likely move the `opaque` bits and pieces into this spec, as the write-only spec hasn't gained much interest from anyone other than me. :)

**Comment by jmajnert** [comment]
> One proposal is to reverse the API such that the FormData object isn't necessary

Could you please elaborate?

**Comment by mikewest** [comment]
Dropped the `FormData` bits entirely as part of the new `LocalCredential::send()` method: https://w3c.github.io/webappsec/specs/credentialmanagement/#send-localcredential

**Comment by jmajnert** [comment]
LGTM, but I think you mixed up `submit` and `send` method names.

**Comment by mikewest** [comment]
You're right, I screwed up the IDL. Fixing!

**Comment by jmajnert** [comment]
I'm on it as well :-)

**Comment by jmajnert** [comment]
https://github.com/w3c/webappsec/pull/232

**Comment by jmajnert** [comment]
https://github.com/w3c/webappsec/pull/233
