### ISSUE TITLE
CREDENTIAL: Why avatarURL MUST NOT be a priori insecure URL

### ISSUE THREAD

**Issue by jmajnert** [w3c/webappsec#200]
Why avatarURL MUST NOT be a priori insecure URL?

**Comment by mikewest** [comment]
Loading an insecure URL would leak data about the user making the request to anyone passively listening on the network. I don't think there's any substantial security risk beyond that, but it's a good-enough reason to lock the feature to secure origins.

**Comment by jmajnert** [comment]
Got it! Thanks
