### ISSUE TITLE
Revise eligibility algorithm to require CORS

### ISSUE THREAD

**Issue by mozfreddyb** [w3c/webappsec#207]
in *[Is resource eligible for integrity validation](http://www.w3.org/TR/SRI/#is-resource-eligible-for-integrity-validation)* the "shared" cache part needs removing

(see #190)

**Comment by metromoxie** [comment]
I believe addressing this is as simple as removing the references to "shared cache" and "publicly cacheable," which I did in the above pull request.

**Comment by metromoxie** [comment]
Just realized there's more controversy here than I thought :-) Let's talk it out here. In particular, I believe @fmarier suggested in #190:
"Does the fact that we don't trigger onerror unless the origin is the same change this reasoning at all?

In the example of an external site loading a publicly cachable intranet resource, we perform the SRI check, but we pretend everything is fine on a bad hash (while cancelling the load): https://w3c.github.io/webappsec/specs/subresourceintegrity/#the-script-element"

It seems that the choices are:
* Require same origin or CORS to use SRI, as suggested by @devd and @annevk
* Or, allow for SRI of publicly cachable resources, and not throw an error in that case. @annevk points out that this would be a bypass of SOP, especially bad on intranets.

I, for one, think that CORS is the only acceptable answer. That's sort of the whole point of CORS, and I don't think we should skip around it.

**Comment by fmarier** [comment]
BTW, is there a performance impact (e.g. extra round-trip) to loading a script using CORS instead of directly?

**Comment by annevk** [comment]
Integrity v1 won't hit those cases. You only hit that with `fetch()` and maybe more complicated versions of `<script>` from the future. But also, attacks > performance.

**Comment by fmarier** [comment]
It sounds like the only safe way forward is to require same-origin or CORS.

**Comment by mozfreddyb** [comment]
Yeah, I don't think we should add another oddity to the web :-)

As sad as it is from a functionality perspective (i.e. SRI being more applicable)…
