### ISSUE TITLE
Pick the shortest reasonable Prefer / upgrade header 

### ISSUE THREAD

**Issue by pde** [w3c/webappsec#216]
We've gone from <tt>Prefer: representation=secure</tt> to <tt>Prefer: https</tt> to <tt>Prefer: tls</tt>.  That's pretty good, 11 characters, 13 bytes on the wire, but should we go further?

An even shorter option which I'm stealing from #212 is <tt>Upgrade: 1</tt>, 10 characters.  Or we could do <tt>Pref: tls</tt>, 8 chacters.  Or go all the way to <tt>TLS: 1</tt> or <tt>HS: 1</tt> for "hypertext secure", 5 characters, 7 bytes on the wire?

There are some aesthetic / clarity arguments for stopping at some point along this line, and I feel I lack data for where to put the pin.

**Comment by mikewest** [comment]
`Prefer` has the advantage of being an existing header, which means that in the best case (when `Prefer` was already being sent by the client), we'd be at 4 characters `,tls`. I think it's reasonable to stop where we are. :)

**Comment by mikewest** [comment]
+@igrigorik

**Comment by igrigorik** [comment]
Is there any case under which "Prefer: https" might affect the caching policy? If so, then we should split it into a separate header due to limitations of Vary. If not, then +1 for "Prefer: https"... because clarity is good, and TLS is not the only secure transport option - e.g. QUIC?

**Comment by mikewest** [comment]
@mnot suggested that `Vary: Prefer` would do what we need (see the example in the doc). Is that not the case?

**Comment by mikewest** [comment]
Also, I forgot about QUIC, et al, and discounted opportunistic encryption. Ugh.

Is there a name that works? At all?

**Comment by igrigorik** [comment]
If "https" is the only token advertised via Prefer, yes that's fine. However, the fact that its an existing header means that other values may be advertised as well, at which point "Prefer: x,y,z" forces "x,y,z" to become part of the cache key, evne if x and y have no business of being part of the cache key. 

I went through same exercise with CH, see: https://github.com/igrigorik/http-client-hints/issues/14

**Comment by mikewest** [comment]
:(

`HTTPS: plz`? We can't use `Upgrade`, as that already has meaning. `U` is a thing, I guess, but I really don't like that it's completely incomprehensible on the one hand and ungoogleable on the other.

**Comment by pde** [comment]
<tt>Sec: Y</tt>, <tt>Sec: 1</tt>, <tt>HTTPS: Y</tt>, <tt>HTTPS: 1</tt>?

**Comment by mikewest** [comment]
`HTTP: S`. *sigh* All of these are, to quote @mnot, horrible horrible. :(

If it's going to be horrible horrible, `HTTPS: 1` seems at least descriptively horrible. Let's run with that for the moment.

**Comment by pde** [comment]
<tt>HTTP: S</tt> may be many kinds of horrible, but it's also poetry :)

**Comment by pde** [comment]
I suspect <tt>HTTPS: 1<tt> is more googleable though.

**Comment by Krinkle** [comment]
@pde It is, and thanks!  :+1:

Searching "[HTTPS: 1 header](https://www.google.co.uk/search?q=%22HTTPS%3A+1%22+request+header)" led me to
[http://www.w3.org/TR/upgrade-insecure-requests/](http://www.w3.org/TR/upgrade-insecure-requests/#preference)
 <sup>(which in turn points here)</sup>

**Comment by glensc** [comment]
`HTTPS: 1` was horrible decision, as such header is quite commonly used in proxy solutions, so backend servers received: CGI variable like `HTTP_HTTPS: 1, on` and that broke quite some setups.

Luckily that `HTTPS: 1` existed only shorty, Chrome/44 only, and was changed to `upgrade-insecure-requests` header later.
