### ISSUE TITLE
Should we allow alternate ports to be configured?

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec#225]
/cc @slightlyoff

**Comment by annevk** [comment]
I don't think so. HSTS doesn't either, right?

**Comment by mikewest** [comment]
I don't think it's worth the complexity.

That said, the port restriction makes it practically impossible to write layout tests in Blink, and makes web-platform-test support more difficult than it should be. Not sure how common that kind of use case is, but it's not nothing.

**Comment by annevk** [comment]
Copying in @jgraham. Not sure I care much about browser-specific infrastructure, but the cross-browser infrastructure is important.

**Comment by mikewest** [comment]
Basically, both Blink's layout tests and wpt's local server run on non-standard ports, which means that neither HSTS nor Upgrade are generally testable. For Blink, we can do tricks like linking to `http://localhost:8443` (which will be upgraded to `https://localhost:8443`), which isn't nothing, but is also fairly unrepresentative of the "Actual World Out There" that we'd like to be testing.

**Comment by mikewest** [comment]
(I have no idea how Mozilla's tests work with regard to TLS...)

**Comment by annevk** [comment]
We have had a pretty strict rule about not introducing additional features for testing or demos and followed that pretty well so far. Which would argue for closing this.

**Comment by jgraham** [comment]
Well, except for the https-requiring things that have a hole punched in them for localhost to make development easier, which is arguably equivalent to "testing and demos".

I don't know what this issue is really about, but I'm not super enthusiastic about requiring root to run tests.

**Comment by annevk** [comment]
I'll explain. There are some features that upgrade HTTP URLs to HTTPS URLs. `upgrade-insecure-requests` is one, HSTS is another. When they upgrade they assume that the port remains the default port for the scheme or remains unchanged if it's a non-default port. However, in testing setups this might not be ideal, but it's unclear whether that needs to be taken into consideration.

**Comment by hillbrad** [comment]
I think we could live with making test execution conditional on the server
being configured to listen on standard ports, so they would only run on the
public gold-standard system or for individuals who have configured their
systems to run that way.

**Comment by mikewest** [comment]
Yup. Closing this out; we can revisit if we become more enthusiastic about it later.
