### ISSUE TITLE
Clarify examples.

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec#226]
We should ensure that example 1 clearly relates to subresource loads, and example 2 clearly relates to subresource loads. Moreover, we should add an example showing what happens if a resource is upgraded, but isn't available over HTTPS (network error).

**Comment by annevk** [comment]
As I said elsewhere, "subresource" is not a term that's grounded and therefore confusing.

**Comment by mikewest** [comment]
For normative statements, I suppose I can agree with you. But for prose? I think there's a reasonable understanding of what a "subresource" is in that context.

Do you have a suggestion for an alternative?

**Comment by annevk** [comment]
Ideally prose and normative text use the same terminology. I don't really have a good word for non-navigation context yet. I was hoping you'd come up with something. So far we have client (navigation/worker) and resource requests.

**Comment by mikewest** [comment]
*shrug* Given "Subresource Integrity", I think the cat is out of the bag on the term. Why not just define it?

**Comment by annevk** [comment]
As I said, "subresource" is already a context and a `<link rel>` value...

**Comment by mikewest** [comment]
And I'm saying that the existence of `<link rel="subresource">` shouldn't mean that we can no longer use a commonly understood word to refer to a commonly understood thing (especially if there's no other commonly used way to refer to that thing).

I don't think there's going to be substantial confusion introduced if we distinguish between a "`subresource` request context" on the one hand, and a "subresource" on the other. *shrug*

**Comment by annevk** [comment]
Fair. So what do we call non-client requests? They're currently called resource requests...
