### ISSUE TITLE
Recursive SRI

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec#228]
It seems problematic that a hash for a stylesheet is meaningless when it has subresources. Integrity must be recursive, otherwise there's no integrity. Am I missing something?

**Comment by mikewest** [comment]
Scripts can load subresources as well, it's not a risk unique to stylesheets. :)

Enforcing integrity for all resources was the point of the CSP directive (that I think is being removed?).

**Comment by annevk** [comment]
Scripts are a bit different, they execute in the global of the document and might use APIs there to load stuff... But yeah, I guess this doesn't fly because of that. But yeah, I guess at some point you can have some directive that enforces things.
