### ISSUE TITLE
SRI: Integration with Fetch

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec#238]
I think point 5 is missing that we basically don't want to give the page any kind of notification until we have end-of-file, no? So any callbacks need to be suppressed until we can verify the integrity and once that is done we can run all three in sequence.

Also, rather than having section 3.9, that should also be a modification to Fetch I think. We should simply return a network error and that will make HTML do the right thing. And since only `script` and `link rel=stylesheet` can set integrity to begin with, not much else is needed.

**Comment by metromoxie** [comment]
@annevk:

To your first point, perhaps I'm misunderstanding, but it seems like it's not that we fundamentally don't want notification until we have an end-of-file. Isn't it okay to get a separate network error earlier, since that's equivalent? What 'notification' are you concerned about?

To your second point, I agree that it would be better to rewrite 3.9 in terms of Fetch. I'm trying to figure out how best to do that. Should it be as simply as something like adding a modification before step 14 in https://fetch.spec.whatwg.org/#process-response-end-of-file such as:
  "If the response's integrity state is corrupt, set response to a network error."

**Comment by metromoxie** [comment]
Also, @mozfreddyb and @devd, you should definitely take a look at this thread as well. We should deal with this before going much further (and @fmarier, but you're already CC'd).

**Comment by annevk** [comment]
@metromoxie in the future `<link>` and `<script>` might expose the underlying response stream. The way that stream gets fed is through those "process response body" callbacks.

I think before step 15 (note that 14 is about the request), you need to check if request has a non-null integrity field (you'll need to add this field to request as well). Then if it does, you need to run substeps where you wait for the entire body to be pushed. Then you do the integrity check using request's integrity field. And if that passes you queue the three callbacks (response, response body, response end-of-file).

Alternatively around step 10 you do a similar check. If integrity is set you simply wait until the body reaches end-of-file and do the check then and modify response to a network error as appropriate.

The second one might be a little nicer since that's where Mixed Content, nosniff, and soon CSP also happen.

**Comment by metromoxie** [comment]
Thanks, that helps a bunch, and the alternative you suggest at step 10 makes particularly a lot of sense. A quick clarification though. In 3.4 step 1, we already add "integrity metadata" to the request. This should be sufficient, right? That is, we don't need to add an additional "integrity field," that you referred to, correct?

**Comment by metromoxie** [comment]
Hm, I suppose your point may have been that we need to establish how the integrity metadata field gets set on the request in terms of Fetch, rather than the per-element definition we currently have?

**Comment by devd** [comment]
Wasn't there some discussion about doing streaming integrity checks? We don't want to write something now that precludes us from doing streaming hashes.

**Comment by metromoxie** [comment]
Streaming integrity is definitely on my list of future features I'd like to see, but can't that be adjusted in the future by modifying Fetch again? That is, I don't think we'd be locking ourselves into anything here by implementing @annevk's algorithm suggestion.

**Comment by devd** [comment]
well, "Alternatively around step 10 you do a similar check. If integrity is set you simply wait until the body reaches end-of-file and do the check then and modify response to a network error as appropriate." seems like would break a future streaming integrity check? I guess you are saying we can always change the integration later?

**Comment by devd** [comment]
Re point 1: Does something like https://github.com/w3c/webappsec/pull/313 help fix it or are you saying we should just remove 3.9 completely and move it all to the modifications to fetch section?

**Comment by annevk** [comment]
@metromoxie yes, you need to associate the metadata with a request. The per-element stuff just invokes Fetch in the end...

**Comment by metromoxie** [comment]
@devd, I suspect you are correct that @annevk would prefer the definition to still go into Fetch, and that 3.9 should be removed.

**Comment by metromoxie** [comment]
Looking more closely, I think #313 definitely helps, but we need to also take out the 'load event' bit, as that's all taken care of by Fetch if we do this right. And, of course, we need to do the same for script as well. I'm taking a whack at this now.

**Comment by metromoxie** [comment]
I started a pull request to begin these changes. @annevk, can you take a quick look at the per-element changes in that pull request? I believe they're the simplifications you're looking for. Tomorrow I plan to work on step 10, as discussed above.

**Comment by metromoxie** [comment]
The latest version of my pull request I believe accurately implements the modifications to Fetch that more fully integrate with it. I believe it also vastly simplifies the changes and algorithms, so I'm a fan of doing it this way. Obviously, this needs careful review from everyone, i.e. @annevk @devd @fmarier and @mozfreddyb. Let me know how it looks.

**Comment by annevk** [comment]
I don't think we should expose corrupt responses as their own entity. We should simply return a network error in that scenario. That's what we do for CORS and a great many scenarios and it ensures APIs automatically dispatch the correct events (`error`) and update all their state correctly (e.g. in the case of `XMLHttpRequest`).

**Comment by annevk** [comment]
Do we really need the `Cache-Control` header with this being restricted to HTTPS?

**Comment by annevk** [comment]
Is `pending` only used for 401 handling?

**Comment by metromoxie** [comment]
Thanks for the comments, @annevk. In the version I merged, I removed "corrupt responses" and the "pending," so I suspect you may be looking at an old version (see https://github.com/w3c/webappsec/pull/391/files for the diff of what I merged). I did, however, leave in a very reduced "Handling Integrity Violations" section that simply suggests catching the network error.

As for Cache-Control, SRI is not restricted to HTTPS, so I believe that, yes, it is necessary.

**Comment by annevk** [comment]
I am looking at https://w3c.github.io/webappsec/specs/subresourceintegrity/#modifications-to-fetch-1

I thought there was no SRI possible without HTTPS... Hmm. Anyway, we need to be clearer about where that header is set as it affects what is exposed to service workers and how CORS works. We should probably set it as part of this algorithm: https://fetch.spec.whatwg.org/#http-network-or-cache-fetch That means it is set after service workers get a go at the request.

Speaking of service workers, should we expose integrity metadata to them?

**Comment by metromoxie** [comment]
Unfortunately, that's not the most up to date. I'll try and merge a pull request to w3c's gh-pages soon, but in the meantime, for the latest check out: http://metromoxie.github.io/webappsec/specs/subresourceintegrity/index.html

I'll take a whack at adding the header to http-network-or-cache-fetch.

It seems reasonable to me to allow SWs to see metadata; is that not automatically taken care of?

**Comment by annevk** [comment]
No, you'd have to add it to the `Request` object. And perhaps `Response` objects should show intermediate vs success? (I'll merge all this into Fetch proper once we've sorted out the details.)

**Comment by metromoxie** [comment]
I believe we do add it to the `Request` object (see Step 1 of https://w3c.github.io/webappsec/specs/subresourceintegrity/#modifications-to-fetch-1). In fact, I believe we've always had it.

Why do you think `Response` objects should differentiate intermediate vs success? Is it just to make sure that the parallel operations do not prematurely finish without the integrity being successfully computed?

**Comment by metromoxie** [comment]
Also, I've updated webappsec/gh-pages, so  https://w3c.github.io/webappsec/specs/subresourceintegrity/#modifications-to-fetch-1 should have my latest modifications now.

**Comment by annevk** [comment]
Step 1 adds it to the "request" concept. It does not alter the API, which is distinct and exposes much less in general: https://fetch.spec.whatwg.org/#request The request concept is what all APIs in the web platform hook into, the Request API is the subset you can use with `fetch()` and service workers.

(I think you're right that responses don't need changes. Either the concept or the API.)

**Comment by metromoxie** [comment]
Got it! Thanks for the clarifications. Pretty embarrassed that I missed that in my first pass :-) I took a first whack at adding this in issue 398. Let me know if it looks good.

**Comment by metromoxie** [comment]
Oh, and I've updated my personal gh-pages with the changes, if you want to look at the compiled version: http://metromoxie.github.io/webappsec/specs/subresourceintegrity/index.html#modifications-to-fetch-1

**Comment by devd** [comment]
closed per commit above, I believe.
