### ISSUE TITLE
SRI: add respec metadata for github & implementation status

### ISSUE THREAD

**Issue by mozfreddyb** [w3c/webappsec#239]
The [permissions api spec](https://w3c.github.io/permissions/) has these additional items, that I would like us to copy :-)

> Participate:
>     We are on Github. 
>     File a bug. 
>     Commit history. 
>     Mailing list. 
> Implementation status:
>     Blink/Chromium 
>     Gecko 

AFAIU this requires just a few more items in the respec config JSON, see https://github.com/w3c/permissions/blob/gh-pages/index.html#L40

WDYT?

**Comment by devd** [comment]
lets do it!

**Comment by metromoxie** [comment]
Hope you don't mind, but I went ahead and implemented these. If it looks good to you, please merge. Thanks!

**Comment by fmarier** [comment]
lgtm, merged :)
