### ISSUE TITLE
CREDENTIAL: Chooser Leakage

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec#246]
Should these avoid service workers? Probably best to define the complete Fetch setup to avoid speculation.

**Comment by mikewest** [comment]
1. If we run with your suggestion in w3c/webappsec#247, we can avoid this entire issue, which is nice.

2. What part of the Fetch setup needs to be specified? Sorry, it's just not clear to me what's missing. :)

**Comment by annevk** [comment]
Just the details of the #concept-request instance. E.g. setting the skip service worker flag might be a thing you want to do.
