### ISSUE TITLE
CREDENTIAL: credential manager hook

### ISSUE THREAD

**Issue by jonathanKingston** [w3c/webappsec#251]
Consider adding in hook for credential managers to listen to `store()` requests without having to override the store prototype to intercept requests.

The credential manager will need to have user approval and gives no real security reductions over the manager monitoring DOM elements.

**Comment by mikewest** [comment]
This isn't something I think we should (or can) mandate with normative language in the specification. Extensions and plugins aren't part of the web platform, they're proprietary bundles of vendor-specific APIs, and the W3C just doesn't have much say in how they work, or how they ought to work.

We can certainly add a note to the spec suggesting that it would be nice for user agents to support 3rd-party credential managers, but that's about as far as I'd suggest that we go.

**Comment by jonathanKingston** [comment]
I meant extensions similar to what is specified in: [app manifests](https://w3c.github.io/manifest/) and the [permission API](https://w3c.github.io/permissions/)

You mentioned also that code would also be able to override the prototype of `navigator.credentials.send` to hook into the saving of passwords, I think this should be highlighted as another alternative as personally I would expect that to be a closed off interface so mentioning that the following would be possible would make it clear:
```
let parentCallback = function () {
};
if ('send' in window.navigator) {
  parentCallback = window.navigator.send;
}
window.navigator.send = function () {
  var that = this;
  return fetch('/credentialslogger', {  
    method: 'POST',
    body: arguments  
  }).then(function () {
    return parentCallback.apply(that, arguments);
  });
};
```

However if this isn't what you intended with the following comment please let me know:
>That is what I meant, but I do totally expect LastPass to inject a content script via their Chrome extension that takes over the API. That's fine. Why would we lock them out?

Does that mean that the API might be locked away in normal web mode in Chrome?

Thanks

**Comment by jonathanKingston** [comment]
@mikewest +1 brilliant work, clear and very helpful to implementers.
