### ISSUE TITLE
CREDENTIAL: Note danger of storing data along with credentials.

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec#253]
Chrome (and other browsers?) treat passwords as distinct from browsing data (cookies, localStorage, etc) when a user elects to clear out traces of her browsing. See chrome://settings/clearBrowserData, for instance.

We should add a considerations section outlining this property, and noting the things to keep in mind when deciding upon the persistence model for new credential types.

**Comment by annevk** [comment]
So if you tie "avatar" in any form (whether URL or Blob) to credentials, you already have this, no? Perhaps instead we need to formulate this differently and say that if the user explicitly clears storage, but keeps credentials, the site does not automatically gets a hold of them but needs to go through UI.

Sharing credentials is enough anyway to restore all browsing data so I don't really see the risk in storing more there...

**Comment by mikewest** [comment]
The clearing browsing data === user mediation bits are already in. See #4 in https://w3c.github.io/webappsec/specs/credentialmanagement/#user-mediation-requirements.

**Comment by annevk** [comment]
I guess we can reconsider the `FormData` subclass idea.

**Comment by mikewest** [comment]
To what end? I'm missing the link between that discussion and this one. :)

**Comment by annevk** [comment]
My idea was that a site could store additional data as part of a credential allowing them to innovate in user space.

**Comment by mikewest** [comment]
I see. Well, Idunno. It seems like we ought to come with a mechanism to allow sites to store things that won't be wiped when a user clears her cookies. It's not clear to me that we should use credentials to anchor that mechanism. I'd suggest that something distinct would be better suited.

**Comment by annevk** [comment]
No the idea would be to store information relevant to the user's credentials, such as other email addresses or phone numbers.

**Comment by annevk** [comment]
Just like browsers might want an icon/avatar, sites might want some other data tied to credentials and have that persisted along with them.

**Comment by mikewest** [comment]
Hrm. Ok. Maybe that's a reasonable thing to add in?

**Comment by mikewest** [comment]
Let's defer the "additional data" discussion until later. I've added a note to the privacy considerations section about the distinction between credential and browsing data to close out the core of this issue.
