### ISSUE TITLE
CREDENTIAL: introduce [[requiresUserMediationSlot]] in the definition of the Credential class

### ISSUE THREAD

**Issue by domenic** [w3c/webappsec#258]
It's confusing that it's referred to throughout but not mentioned when defining the class.

**Comment by mikewest** [comment]
Yeah, I need to get rid of the slot in favor of an origin-based scheme. That's https://w3c.github.io/webappsec/specs/credentialmanagement/#issue-e536848c, which I'll update to refer to this bug.
