### ISSUE TITLE
CREDENTIAL: federated example could be a bit more detailed

### ISSUE THREAD

**Issue by domenic** [w3c/webappsec#260]
I'm still hazy on how federated credentials are supposed to work, practically speaking. I think expanding on the `// Do something specific for each supported federation` in the example would help a lot.

Is this a correct guess for something that could go there?

```js
case "https://www.facebook.com/":
  // https://developers.facebook.com/docs/facebook-login/login-flow-for-web/#logindialog
  FB.login(function (response) {
    if (response.status === "authorized") {
      // Can now use FB.api() calls
    } else {
      // Explain to the user that we would really like them to click "Log me in"
    }
  });
```

maybe even adding a similar Google example alongside this, in another `case` clause, would be good to really drive home how the application does most of the work.

**Comment by mikewest** [comment]
Great idea, thanks.
