### ISSUE TITLE
SECURE: DOM-exposed property?

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec#263]
As noted briefly in #262, it might be a good idea to add an `isPrivilegedContext` (or whatever) property to the global object to allow feature detection.

**Comment by annevk** [comment]
Thought: make it an auto-granted permission named "privileged". Also, given the number of APIs we want to make privileged-only they could perhaps be used as well. E.g. a check for the service worker stuff.

**Comment by mikewest** [comment]
I'm not sure whether it's better to drop the API entirely. Chrome is just throwing/resolving with errors, which seems like a pretty reasonable thing to do. Modeling it as a permission is an interesting idea.

**Comment by mikewest** [comment]
This still might be interesting to do, if only to resolve the oscillation noted in w3c/webappsec#406.

**Comment by mikewest** [comment]
On IRC, @annevk suggested that he wasn't happy about a `navigator.permissions.query({ 'name': 'secureContext' })` mechanism anymore. I do think it's probably worth exposing something, but I'm fairly agnostic on the format.

@domenic, @annevk, @slightlyoff: Can I just defer to you three with regard to web-facing API design? I'd just add a boolean to the global object, but that's probably a bad idea for some set of very good reasons. :)

**Comment by annevk** [comment]
`self.isSecureContext` is probably fine actually. We've been a bit shy adding things to the global, but there's not really a better object.

**Comment by mikewest** [comment]
WDYT of https://w3c.github.io/webappsec/specs/powerfulfeatures/#detection?

**Comment by annevk** [comment]
I think you want to use the global of the getter rather than the incumbent settings object.

(Also, given https://fetch.spec.whatwg.org/#fetch-method and similar such patterns, perhaps we should figure out some way to extend all globals at once in a simpler manner.)

**Comment by mikewest** [comment]
> I think you want to use the global of the getter rather than the incumbent settings object.

Right you are.

> (Also, given https://fetch.spec.whatwg.org/#fetch-method and similar such patterns, perhaps we should figure out some way to extend all globals at once in a simpler manner.)

Service Workers did things this way. If I'd checked Fetch first, I would have done it that way. :)

Perhaps @heycam wants to invent some new syntactic sugar for this kind of thing?

**Comment by domenic** [comment]
Would it work to just add an new mixin interface to HTML that both Window and WorkerGlobalScope mix in? And then people can partial that? Shouldn't require changes to IDL, unless I am missing something.

**Comment by annevk** [comment]
@domenic I was thinking that too.

**Comment by mikewest** [comment]
Closing this out. If y'all would like me to adopt some futuristic HTML thing, let's do it in another issue.

**Comment by annevk** [comment]
Fair.
