### ISSUE TITLE
CREDENTIAL: expose type so you can avoid instanceof?

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec#271]
instanceof is not reliable across globals.

**Comment by mikewest** [comment]
Hrm. What's the right way to define such an attribute? Something like "This attribute [reflects] the type name of the credential's interface."?

**Comment by annevk** [comment]
I'm not sure, but I would not make them identical. I would keep `type` short and sweet.

**Comment by adrianhopebailie** [comment]
This mapping (string passed into `get()` as type filter -> type name of interface) impacts extensibility as far as I can tell.

When an app stores a `Credential` object (or custom-subclass of it) how does it retrieve it later?

If I do this:

```javascript
navigator.credentials.store(
  new AgeVerificationCredential({
    "id": "person_12345_age",
    "type": "age", //Do I need this?
    "isOlderThan18": true,
    "isOlderThan21": true,
    "issuer": "http://credentialissuer.com",
    "signature": { ... },
  })
);
```
Would I do this?

```javascript
navigator.credentials.get({
  "types": [ "password", "age" ],
});
```

OR

```javascript
navigator.credentials.get({
  "types": [ "PasswordCredential", "AgeVerificationCredential" ],
});
```

**Comment by mikewest** [comment]
To what extent would either of the options you suggest hinder extensibility?

> //Do I need this?

I hope not. :) If we run with a shorter name, I'd planned on defining the property at the interface level. That is, every `PasswordCredential` would return `password` as it's type. Every `FederatedCredential` `federated`, etc.

**Comment by adrianhopebailie** [comment]
>To what extent would either of the options you suggest hinder extensibility?

I'm not suggesting they would, I was merely pointing out that not having a `type` property is less flexible. i.e. +1 to this suggestion from @annevk 

> If we run with a shorter name, I'd planned on defining the property at the interface level. That is, every PasswordCredential would return password as it's type. Every FederatedCredential federated, etc.

I assumed as much. That's great. It still allows future implementors to define something like a sub-class called `AgeVerificationCredential` which has a type of `http://ageverifiers.com/credential/' if that's how the type is defined in something like linked-data.

**Comment by mikewest** [comment]
Ah, ok. Sorry for the misunderstanding. I read "impacts extensibility" as "negatively impacts extensibility", which I suppose says something about me. :)

**Comment by mikewest** [comment]
I've taken a pass at this by defining an internal slot on `Credential` which is overwritten by the inheriting interfaces. Seems sane. WDYT?

**Comment by annevk** [comment]
lgtm

**Comment by mikewest** [comment]
Huzzah!

**Comment by adrianhopebailie** [comment]
:+1:
