### ISSUE TITLE
CREDENTIAL: filter is underdefined

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec#273]
Since you allow a custom object and not a dictionary you need to define all error handling yourself. E.g. what happens when [[Get]] throws?

**Comment by mikewest** [comment]
Is there a reasonable way to allow custom objects that doesn't involve defining my own error handling? :)

Failing that, is there a good source from which to cargo-cult my way to covering all the possible failure modes?

**Comment by annevk** [comment]
Well you could just make it a dictionary.

**Comment by mikewest** [comment]
How does this look?

**Comment by annevk** [comment]
Seems reasonable. Not sure how that typedef approach works though.

**Comment by mikewest** [comment]
Let's pretend it works. We'll come back to it if/when we actually extend the API.
