### ISSUE TITLE
CREDENTIAL: Interface PasswordCredential does not have [NoInterfaceObject] but inherits from interface LocallyStoredCredential which does

### ISSUE THREAD

**Issue by AxelNennker** [w3c/webappsec#291]
I have put some of the WebIDL from the spec into a file and ran it through Mozilla's WebIDL.py which gives the above error message.

I think this mean there is no way to specify iconURL for a PasswordCredential because currently LocallyStoredCredential is a NoInterfaceObject.

--Axel

Is it possible to put the WebIDL into separate files, include them into the spec-source, concatenate them into one Credentials.webidl file and run that through a validator?
http://www.w3.org/2009/07/webidl-check
The w3c webidl-check does not complain about this webidl but I think WebIDL.py might have a point.
http://www.w3.org/2009/07/webidl-check?doc=https%3A%2F%2Fraw.githubusercontent.com%2FAxelNennker%2Ffirefox_credentials%2Fmaster%2FCredentials.webidl&output=html

**Comment by mikewest** [comment]
Interesting. That's pretty clearly the impact of http://heycam.github.io/webidl/#NoInterfaceObject. Hrm.

@domenic: I think you're the one who (months and months ago) suggested making `Credential` a `[NoInterfaceObject]`. I don't particularly mind dropping that restriction, though there's not much reason in the current API to construct either of those objects. WDYT?

**Comment by domenic** [comment]
I think I suggested using implements instead of inherits. So I think the chain should be:

- [NIO] Credential
- [NIO] LocallyStoredCredential
- LocallyStoredCredential implements Credential
- [Constructor] PasswordCredential
- PasswordCredential implements LocallyStoredCredential

This makes Credential and LocallyStoredCredential into "mixins" rather than part of the inheritance hierarchy. Which makes sense, since they aren't sensible classes (you can't construct them).

**Comment by mikewest** [comment]
Makes sense to me.

Regarding the suggestion to extract the IDL bits into separate files, I don't have any fundamental objection to doing that, but let's wait until the dust settles before working through the tooling that would be necessary to inject the IDL files into the right places into the document at build time. As long as it's still changing daily, it's simpler to do all as part of the same document.

**Comment by domenic** [comment]
You could also write tooling that extracts the IDL from the document; should be pretty simple with a basic HTML parser.

**Comment by mikewest** [comment]
Actually, now that I think about it, we basically have this already at the bottom of the document: https://w3c.github.io/webappsec/specs/credentialmanagement/#idl-index
