### ISSUE TITLE
CREDENTIAL: mismatch of "type" value between note and example

### ISSUE THREAD

**Issue by AxelNennker** [w3c/webappsec#294]
The text in 
http://w3c.github.io/webappsec/specs/credentialmanagement/#passwordcredential

[[type]]
    All PasswordCredential objects have their [[type]] slot’s value set to password.

while the example 
http://w3c.github.io/webappsec/specs/credentialmanagement/#examples-password-signin
has this code:
if (credential.type == "PasswordCredential") {

I think the text should be changed to:
[[type]]
    All PasswordCredential objects have their [[type]] slot’s value set to "PasswordCredential".

The PR is here:
 CREDENTIAL: mismatch of "type" value between note and example #293

**Comment by mikewest** [comment]
Thanks for the PR, but, as I noted there, we're using `password` as the type, not the whole long interface name. See the discussion at https://github.com/w3c/webappsec/issues/270.
