### ISSUE TITLE
UPGRADE: Rework 'navigation set'.

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec#295]
In https://github.com/w3ctag/spec-reviews/pull/54, @diracdeltas notes:

> ### ISSUE: Need Example for Upgrade Insecure Navigations Set
> 
> It would be nice to have an example of a CSP directive with an upgrade insecure
> navigations set in the draft.

This isn't something I intended to expose via the directive, but is instead an implementation detail of the nesting behavior. That is, if `example.com` is loaded at top-level, it upgrades navigational requests to `example.com`. If it loads `not-example.com` in an iframe, navigational requests to `example.com` should still be upgraded in _that_ new context.

If, however, `not-example.com` _also_ sends the upgrade header, then navigations to `example.com` and `not-example.com` should be upgraded. To support this use case, each Document needs to track the origins which ought to be upgraded in its context.

We could probably simplify this by making the list global for everything under the top-level browsing context, now that I think about it.

**Comment by diracdeltas** [comment]
I see, so the upgrade navigation set for a context is the union of the upgrade navigation sets of its ancestors and its own origin if it sends the upgrade header.

**Comment by mikewest** [comment]
Duping this into https://github.com/w3c/webappsec/issues/184; if we end up with two directives there, this will turn into something quite self-explanatory. If not, I'll have to poke at the definition there anyway.
