### ISSUE TITLE
CREDENTIAL: Why are all the interfaces [NoInterfaceObject] and using mixins instead of inheritance

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webappsec#309]
Both are a little odd.  And then then the mixin interface is getting passed as an argument...

**Comment by bzbarsky** [comment]
Also, I believe that apart from Transferable, which I'm not sure how implementations handle, there are no other instances of a mixin being passed as an argument in the web platform.  I really don't think we should be adding instances of that pattern.

**Comment by mikewest** [comment]
This was my understanding of @domenic's suggestions in earlier bugs. I don't have strong opinions about it either way.

**Comment by bzbarsky** [comment]
Which bugs were those?

Basically, do you want an is-a relationship between PasswordCredential and Credential?  If you do, you should be using interface inheritance...

**Comment by domenic** [comment]
Since Credentials can't actually exist, it doesn't make sense to have an is-a relationship with them. PasswordCredentials and FederatedCredentials share a few properties, so encapsulating that in a mixin makes sense.

**Comment by bzbarsky** [comment]
> Since Credentials can't actually exist

Then in what sense does it make sense to have a method whose argument is a Credentials?

**Comment by bzbarsky** [comment]
In particular, let's look at http://w3c.github.io/webappsec/specs/credentialmanagement/#dom-credentialcontainer-storecredential which then calls http://w3c.github.io/webappsec/specs/credentialmanagement/#store-credential which does a switch on the credential types (with "this is an extension point" weasel wording), and then calls http://w3c.github.io/webappsec/specs/credentialmanagement/#store-locallystoredcredential which then does "switch on credential's interface" (whatever that means).  It seems to me this would be a lot more clear if it were just honest about taking a union type and then just switched on what type it was passed, which is an operation that's actually well-defined.  And would incidentally make sure that no one comes up with some silly scheme in which different credentials are not actually distinguishable but the algorithm expects to distinguish them, because that would be automatically caught by IDL's union handling.

**Comment by mikewest** [comment]
> do you want an is-a relationship between PasswordCredential and Credential

The relationship is intended to be 'is-a', with `Credential` and `LocallyStoredCredential` embodying those properties that all their subclasses inherit. I was inheriting, actually, until https://github.com/w3c/webappsec/issues/291 helped me realize that I can't inherit from a `[NoInterfaceObject]`. I don't particularly mind adding `Credential` and `LocallyStoredCredential` as visible ancestors if that's the right way to express the relationship.

> which does a switch on the credential types (with "this is an extension point" weasel wording)

The "weasel wording" was intended to explicit and helpful. :( What's a better way of making it clear that future credential types are intended to hook into the flow here and at the other extension points?

> "switch on credential's interface" (whatever that means)

Can you help me construct a better way to say "Do this for `PasswordCredential`, and do this for `FederatedCredential`"? That is, if I follow your advice and allow a union type, what prose ought I use to distinguish between them clearly?

**Comment by bzbarsky** [comment]
> I was inheriting, actually, until #291 helped me realize that I can't inherit from a [NoInterfaceObject]

See, here is the crux of the issue.  If we want an is-a relationship, then we want `Credential` to not be `[NoInterfaceObject]`, imo.  @domenic might disagree, of course, but I think he's also disagreeing on whether there should be an is-a relationship...

OK, so we have two options.  We can either make `LocallyStoredCredential` inherit from `Credential` and make `PasswordCredential` inherit from `LocallyStoredCredential` and then have the argument type be `Credential` and have the prose talk about either "if credential implements `PasswordCredential`" if you want that prose to apply to interfaces derived from `PasswordCredential` or "if credential's primary interface is `PasswordCredential`" if you don't want it to apply to derived interfaces.

Or you can use a union type for the argument, have the prose either switch on the type the union decided the argument is or talk about "if credential is a `PasswordCredential`" (which is sensible, because now you're defining it in terms of what the union is seeing), and then you can either keep the current "implements" setup or use inheritance, however you prefer.

**Comment by bzbarsky** [comment]
Also, whatever you decide to do for the argument you should do for the type the `Promise` return value is parametrized on as well.  Returning a `Promise` parametrized over a mixin doesn't really make sense.

**Comment by bzbarsky** [comment]
Oh, and the "weasel wording" is probably OK in the is-a world but in the mixin world the IDL would need to be changed anyway to allow the new types.

**Comment by domenic** [comment]
Union type makes a lot more sense. Since you're not doing polymorphism anyway, but instead just switching on the type, that should be reflected in the type signature.

**Comment by heycam** [comment]
The IDL would need to change in the union type world, too. Not that that is necessarily a bad thing – are we going to be allowing extensions without revising this spec, and how many extensions are we thinking we'll get, anyway?  I don't have a particularly strong view about whether union types or is-a modelling is better. While there may not be much polymorphic behaviour of `Credential` objects (although I bet you that implementations of this will use polymorphism to implement the `type` IDL attribute), I still think it's valid to model the fact that all kinds of credentials have an ID and type string using a `Credential` superinterface.

Either way, I don't think mixins are the answer.

**Comment by mikewest** [comment]
Thank you for your feedback, @heycam, @domenic, and @bzbarsky. Sorry I haven't gotten back to this until now: I really do appreciate the time you put into this discussion.

I think I generally agree with @heycam; mixins don't seem to model things the way I expect them to work. I do expect a number of additional credential types to be proposed going forward, and, as noted above, `type` will almost certainly be implemented via polymorphism. *shrug* I'll flip over to inheritance. We can argue about it again when this is solid enough to bring back to the TAG for a re-review . :)
