### ISSUE TITLE
SRI: Do we need to make changes to HTML5's fetch too?

### ISSUE THREAD

**Issue by fmarier** [w3c/webappsec#316]
While working on #313 and #315 I realized that both the [link](http://www.w3.org/TR/html5/document-metadata.html#concept-link-obtain) and [script](http://www.w3.org/TR/html5/scripting-1.html#prepare-a-script) sections of the HTML5 refer to a [potentially CORS-enabled fetch](http://www.w3.org/TR/html5/infrastructure.html#potentially-cors-enabled-fetch) which itself refers to the HTML5 [processing model](http://www.w3.org/TR/html5/infrastructure.html#fetch).

We have a section which modifies the [Fetch](https://fetch.spec.whatwg.org/) spec, but do we also need to update the [equivalent HTML5 section](http://www.w3.org/TR/html5/infrastructure.html#fetch)?

**Comment by annevk** [comment]
No, HTML will be updated in time to reference Fetch. We should just explain things in terms of Fetch.

**Comment by fmarier** [comment]
Sounds good to me.
