### ISSUE TITLE
SRI: Broken markdown in Sections 3.1 and 3.2

### ISSUE THREAD

**Issue by fmarier** [w3c/webappsec#320]
The hashes in the examples for both sections are partially in bold. We should fix that!

**Comment by devd** [comment]
Not sure I understand: they look fine to me. Can you check again? @mozfreddyb

**Comment by fmarier** [comment]
![markdown](https://cloud.githubusercontent.com/assets/167821/7669235/5c87fbcc-fcbb-11e4-939f-2c8f3f43856f.png)

It's hard to see because the "links" are purple and not underlined, but I've highlighted them above.

**Comment by devd** [comment]
aah I did see that :)

This seems like a thing that ReSpec does: I think it is trying to do some basic code highlighting for the code blocks based on google-code-prettify. @darobin do you know how to tell respec that this is not to be prettified?

**Comment by darobin** [comment]
Can you give me a link so I can check what's going on?

**Comment by mozfreddyb** [comment]
@darobin https://w3c.github.io/webappsec/specs/subresourceintegrity/#integrity-metadata-1

**Comment by darobin** [comment]
You're including class `highlight`. That... highlights stuff :) http://www.w3.org/respec/ref.html#highlight Just remove the class; if it doesn't stop highlighting *then* we have us a bug.
