### ISSUE TITLE
[SRI] Remove browser UI integrity use case?

### ISSUE THREAD

**Issue by hillbrad** [w3c/webappsec#321]
Section 1.2.1 lists a user agent which composes its UI from HTML as a potential use case for SRI.  I'm not sure this is a good example, first because I struggle to imagine a set of trust boundaries which would allow a malicious party to modify files describing trusted UI but not also be able to subvert the integrity mechanism.  Also, since file schemes are pretty much excluded, this makes it even more difficult to conceptualize how this would be implemented.  I think we are better off leaving this out than having a potentially confusing example.

**Comment by fmarier** [comment]
I'd be OK with removing that example.

**Comment by mozfreddyb** [comment]
I'm OK with removing, but I also think that we should have more than just one use case in our spec, as it will make our spec goals clearer.

**Comment by fmarier** [comment]
I think the pull request didn't actually address @hillbrad's underlying concern here: browser UI is not a good example for SRI.

Why not just remove it? We still have two different uses cases:

1. you want to outsource one of your own resources to a CDN
2. you want to rely on an external resource as long as it doesn't change

**Comment by devd** [comment]
just to make up a scenario: a "browser" on your car that keeps the UI resources on a hard disk outside.

**Comment by devd** [comment]
I am so confused .. I didn't close this again. Why did it get closed?

**Comment by fmarier** [comment]
It was closed by a commit, so maybe someone merge the master branch onto gh-pages?

**Comment by mozfreddyb** [comment]
I find a browser UI an interesting use case, but I'm not gonna insist on it being in the spec :-)

**Comment by hillbrad** [comment]
You don't have to remove it.  Just didn't seem obvious to me.

**Comment by fmarier** [comment]
Since others like this example and nobody objects to leave it in the spec, let's close this issue.
