### ISSUE TITLE
[SRI] Mash-up use case is weak or wrong?

### ISSUE THREAD

**Issue by hillbrad** [w3c/webappsec#323]
The use cases section lists a mash-up author wanting to "make sure her creation remains in a working state"

Integrity metadata is not communicated to the remote server to allow it to continue presenting a correct representation, so it actually makes a mash-up more brittle, as semantically inconsequential changes might cause a critical subresource to fail to load.  This is a deliberately engineered tradeoff: by not hinting to a remote server which representation they expect, a few sites that use SRI for something like jQuery can act as canaries to detect modification of resources depended upon by a much larger population.

**Comment by fmarier** [comment]
Removed in https://github.com/w3c/webappsec/pull/298
