### ISSUE TITLE
[SRI] Mention MIME-type chameleons in Security Considerations?

### ISSUE THREAD

**Issue by hillbrad** [w3c/webappsec#324]
The spec mentions annotating the expected MIME type as a potential new metadata, but we do not mention why this might be necessary.  Perhaps it is worth noting in the security considerations section that the interpretation of a resource depends on its MIME type, the current spec does not specify that because most user agents enforce MIME type constraints implicitly on <link> and <script> elements, but confusion might be possible if, e.g. the same resource could be interpreted as javascript or vbscript, depending on the Content-Type header, with potentially very different semantics.

**Comment by fmarier** [comment]
@hillbrad do you mean something like https://github.com/w3c/webappsec/pull/302?

**Comment by hillbrad** [comment]
Yes. I'm not sure this isn't still an actual potential issue in a Microsoft
Edge implementation that does vbscript.

**Comment by mozfreddyb** [comment]
let's continue in #302.
