### ISSUE TITLE
SRI: Cannot use jQuery in our example

### ISSUE THREAD

**Issue by fmarier** [w3c/webappsec#327]
We currently have this example in the spec:

    <script src="https://code.jquery.com/jquery-1.10.2.min.js"
            integrity="sha256-C6CB9UYIS9UJeqinPHWTHVqh/E1uhG5Twh+Y5qFQmYg="
            crossorigin="anonymous">

but that doesn't work because `code.jquery.com` doesn't expose the required CORS header.

We need to either get them to add it or otherwise we need to change this example to something else.

Does anybody have contacts at jQuery or MaxCDN?

**Comment by annevk** [comment]
Just change it to `https://example.com/example-framework.js`. Situation might have changed a decade from now too.
