### ISSUE TITLE
[CREDENTIAL] OAuth 2.0 is not an authentication protocol

### ISSUE THREAD

**Issue by tbroyer** [w3c/webappsec#330]
> A federated identity provider is an entity which a website trusts to correctly authenticate a user, and which provides an API for that purpose. OAuth2 [RFC6749] is an example of such an API, used by a number of providers.

OAuth 2.0 is **not** an authentication protocol: http://oauth.net/articles/authentication/

**Comment by mikewest** [comment]
I should have written something like OpenID. Thanks for the heads up; I'll fix the text.
