### ISSUE TITLE
Broken link nist.gov PDF

### ISSUE THREAD

**Issue by tagawa** [w3c/webappsec#331]
The link to the “Descriptions of SHA-256, SHA-384, and SHA-512” document is returning a 404. The current link points to http://csrc.nist.gov/groups/STM/cavp/documents/shs/sha256-384-512.pdf and I can't find a working alternative link. Another <a href="http://www.antd.nist.gov/iip_pubs/rfc3602.txt">NIST document</a> points to http://csrc.nist.gov/cryptval/shs/sha256-384-512.pdf but that's a broken link too.

**Comment by mozfreddyb** [comment]
According to the [NIST secure hashing page](http://csrc.nist.gov/groups/ST/toolkit/secure_hashing.html#Approved%20Algorithms) all of their hashing standards are now in [FIPS PUB 180-4: Secure Hash Standard (SHS)]( http://csrc.nist.gov/publications/fips/fips180-4/fips-180-4.pdf)

Seems like an easy fix. Do you want to send a pull request, @tagawa? ;)

**Comment by tagawa** [comment]
Well found. I've sent a pull request: #333
