### ISSUE TITLE
SRI: note about CORS headers for resources behind firewalls

### ISSUE THREAD

**Issue by fmarier** [w3c/webappsec#337]
From @annevk:

"The specification should probably point out that for resources behind
a firewall, CORS should only be used with an origin (not *) and only
for origins that are behind the same firewall."

**Comment by devd** [comment]
That is a weird note. I also think this is a broader problem of CORS and it is not clear why the spec should address this. At best, we can link to the CORS spec that should discuss the issues with setting * for resources ACL'ed by IP and not cookies.

**Comment by devd** [comment]
@annevk wdyt?

**Comment by devd** [comment]
I am closing this since I don't think that we should do this nor has anyone else chimed in for 3 weeks now. Please reopen if needed.

**Comment by annevk** [comment]
Mkay. I just mentioned it since it seems like a lot of people didn't understand this in the context of SRI.
