### ISSUE TITLE
[SRI] "Authorization" is a request header, not a resource (response) header

### ISSUE THREAD

**Issue by hillbrad** [w3c/webappsec#345]
Algorithm in section 3.3.2 asks if "resource" contains the "Authorization" header.  Authorization is a request header, not a response header, so a resource will never have it.  Whether the header is sent as part of the request is controlled by the CORS mode. (anonymous / use-credentials)  

Suggestion: Remove the Authorization header from this algorithm.

**Comment by devd** [comment]
Mind jumping in on #305, since there is some talk of just killing this headers stuff outright?

**Comment by devd** [comment]
since we just killed the headers.

**Comment by metromoxie** [comment]
sgtm
