### ISSUE TITLE
[SRI] getPrioritizedHashFunction should be a normative definition

### ISSUE THREAD

**Issue by hillbrad** [w3c/webappsec#346]
Section 3.2.2 states that a user agent MUST provide a means of determining algorithm priority, but doesn't normatively specify an API, only gives the example of "getPrioritizedHashFunction(a, b)".  If we are going to be able to test this requirement as a MUST, it needs to be normatively defined with a way to access it.

**Comment by devd** [comment]
(hah! didn't see this, I need to fix my notification settings.)

I don't believe the idea was that getPrioritizedHashFunction would be something accessible via JS. I don't believe any of the implementations do that. That was a generic: UAs must define a priority listfor their implementations and the function is only to allow defining the algorithm more cleanly.

@metromoxie @fmarier @mozfreddyb do any of the implementations define this?

**Comment by mozfreddyb** [comment]
Yeah, I think the idea was to describe an API that can be used in our algorithms without mandating an order that describes how to prioritize two hash functions. E.g., it is hard to judge for two hash functions with the same output size that come from different hash families. We wanted the user agent to decide freely.

**Comment by hillbrad** [comment]
1) My question is not whether the spec should mandate the priority ordering
or choice of hash functions, it is whether a user agent implementation
should reveal its choices to applications it hosts through an explicit API.
(it can always be discovered)

It can be nice to do be able to answer questions like: "What algorithms are
supported by my users' browsers, and in what ordering?", or even "what set
of hashes should I send to this specific browser?" through direct feature
detection, without having to enumerate through side effects or UA sniff and
manually map to published orderings.

2) If we choose not to reveal those preferences explicitly, can we please
add a clarifying sentence like I've seen elsewhere: "The implementation is
vendor-specific, and the interface provided is not exposed to the web."

**Comment by devd** [comment]
I think 1 could be an option in the future, but we should add 2 right now. Sorry, since I had just reviewed your tests, I got a bit confused.

**Comment by hillbrad** [comment]
OK.  Test cases are just going to have to assume that 512 > 384 > 256 for
now, then.  Will update the PR shortly.

**Comment by fmarier** [comment]
> do any of the implementations define this?

Mine doesn't. I [use internal constants](https://bitbucket.org/fmarier/mozilla-central-mq-992096/src/83e52f6d764173b06d07ee3966774c6be53ff968/bug992096.patch#cl-1224) to figure out the strongest algorithm.
