### ISSUE TITLE
CREDENTIAL: Extension points discussion suggests things that are not possible in Web IDL

### ISSUE THREAD

**Issue by bzbarsky** [w3c/webappsec#349]
In particular it's suggesting using a union of two dictionary types, but that's not viable: a dictionary is just an object, and it's impossible to tell from the object _which_ dictionary is meant.  So dictionary types are not distinguishable in IDL, and a union of type dictionary types is invalid IDL.

**Comment by mikewest** [comment]
IDL. :(

So, accept `object` and do duck typing?

**Comment by bzbarsky** [comment]
Well... what behavior are you aiming for?  That is, ignore IDL syntax for now (it's _always_ the wrong place to start worrying about a problem) and describe to me how you envision an actual implementation working here.  An object is passed in.  What does the implementation do with it?

**Comment by mikewest** [comment]
Actually, now that I look at where this hooks in, I think we're already designing around it in https://github.com/w3c/webappsec/pull/292#discussion_r29045379 (which I need to pick up again and turn into a patch).

That is, I don't think we need the type-specific dictionaries as arguments to `request()`, but can instead fold them into a more generic filtering mechanism, tied to `type` names and type-specific matching functions rather than unions of dictionary types.

**Comment by mikewest** [comment]
Does the approach in e6c11ed address your concerns, @bzbarsky? I'm hopeful that defining the filtering mechanism as a dictionary of dictionaries both addresses the extensibility concerns of #292, and the implementation concerns here.

**Comment by mikewest** [comment]
(The new IDL is visible at https://w3c.github.io/webappsec/specs/credentialmanagement/#idl-index)

**Comment by bzbarsky** [comment]
Trying to figure out how this interacts with "get", I noticed that the links to "get" in the examples in that draft seem to point to http://dev.w3.org/csswg/css-regions-1/#dom-namedflowmap-get which is presumably not what's intended...

I assume the relevant "get" is <https://w3c.github.io/webappsec/specs/credentialmanagement/#dom-credentialcontainer-gettypes-options>?   And that the only consumer of the dictionary so far is <https://w3c.github.io/webappsec/specs/credentialmanagement/#federatedcredential-matching>?

If so, the setup seems sane, modulo the following issues:

1.  This IDL puts `?` after all the dictionary types, which is not valid IDL.  Dictionary types are automatically nullable, with null representing the empty dictionary.
2.  The second argument of `get` needs to be optional, since it's a dictionary in trailing position without required members.  The spec examples that do `get(["password"])` assume this behavior anyway, of course.
3.  There seems to be an unused `password` member in `CredentialRequestOptions`.  Why is it there?
4.  In https://w3c.github.io/webappsec/specs/credentialmanagement/#federatedcredential-matching steps 1 and 2, you can't really talk about `undefined` or `null`: those are JS values, not IDL values.  Furthermore, they make no sense for a dictionary anyway, since as I said above `null` represents an empty dictionary, and so does undefined.  So in practice a `CredentialRequestOptions` will always have a member named `federated` and this member will always be "present" (in the IDL dictionary member sense).  So you can just set `federated` to the `federated` member of the `CredentialRequestOptions` and then move on to what is now step 3.
5.  In the current steps 3 and 4 of that algorithm, you want to talk about "if the providers member is present in `federated`", I think.

All of those are mechanics, though.  The end result ends up being the behavior you have in mind, and it's a behavior that makes sense as far as I can tell.

**Comment by mikewest** [comment]
> Trying to figure out how this interacts with "get", I noticed that the links to "get" in the examples in that draft seem to point to http://dev.w3.org/csswg/css-regions-1/#dom-namedflowmap-get which is presumably not what's intended...

Bikeshed is weird. I'll fix it. (cc @tabatkins, I would have expected a warning if an autolink to a method defined in this document was being overridden by one in a different document :/ )

> I assume the relevant "get" is https://w3c.github.io/webappsec/specs/credentialmanagement/#dom-credentialcontainer-gettypes-options?

Correct! Sorry for the confusion.

> And that the only consumer of the dictionary so far is https://w3c.github.io/webappsec/specs/credentialmanagement/#federatedcredential-matching?

Yes.

Thank you for the nits; they're illuminating. I'll fix them once I figure out how to bend Bikeshed to my will. :)
