### ISSUE TITLE
[CSP] path-part should be represented by path-abempty

### ISSUE THREAD

**Issue by shekyan** [w3c/webappsec#361]
In Source List Syntax [section 4.2] (https://w3c.github.io/webappsec/specs/content-security-policy/#source-list-syntax) ABNF grammar,  shouldn't *path-part* be *path-abempty* production, rather than *path*?

**Comment by michaelficarra** [comment]
Currently, using the `path` grammar is ambiguous because we can't tell where host-part or port-part ends and path-part begins. Using `path-abempty` forces the path to start with a `/`, which is disallowed in host-part and port-part.

**Comment by shekyan** [comment]
This issue was moved to w3c/webappsec-csp#89
