### ISSUE TITLE
SRI: additional Acknowledgements?

### ISSUE THREAD

**Issue by mozfreddyb** [w3c/webappsec#362]
Re-visiting old threads, @lcamtuf and @sirdarckcat  provided meaningful feedback about cross-origin attacks (which lead to the cross-origin leakage section, 5.3).

@annevk provided meaningful feedback about how to formally specify an integration with *fetch*. His persistence to prevent us from breaking the web and exposing intranets seems noteworthy to me :wink:

**Comment by fmarier** [comment]
I think the answer to the question in the bug title is "yes" :)

**Comment by devd** [comment]
hahahah yes, although I think a more general "all the participants of teh webappsec wg and those who gave feedback on the public-webappsec mailing list" is warranted
