### ISSUE TITLE
SRI: explain how to parse tokens

### ISSUE THREAD

**Issue by devd** [w3c/webappsec#366]
The draft does not define how to parse tokens, only split a list of tokens on spaces. It's clear from examples what is meant, but this should be made explicit.

**Comment by fmarier** [comment]
I guess implementers need to look at three things:

* Section 3.1 says there are three components.
* Step 6 of Section 3.3.5 extracts each of these components.
* The separators are included in the grammar of Section 3.6

**Comment by devd** [comment]
hmm .. that's not too bad. @wbl what do you think?

**Comment by wbl** [comment]
Step 6 should tell implementors to parse using the grammar then, just to clear up confusion. Token isn't actually defined in the grammar.

**Comment by devd** [comment]
closed per above merge, I believe.
