### ISSUE TITLE
[EPR] clarify behavior when EPR:1 header not set

### ISSUE THREAD

**Issue by hillbrad** [w3c/webappsec#375]
Is the EPR:1 header only a hint to look for a policy?  In such case, it only makes sense if the policy comes from a well-known location and we want to indicate that the UA should check for it.  Perhaps it is redundant to just re-using the Link header with an appropriate relation and location specified in this case?

Or is the EPR:1 header an opt-in to policy enforcement?  i.e. If I have a policy I have previously loaded (or an WebApp Manifest policy which includes EPR data elements) and it includes as in-scope a resource which does not set the EPR header, should the policy still be enforced?

**Comment by randomdross** [comment]
EPR:1 is an opt-in to policy enforcement.  If no policy exists, the default policy is used.  The idea is that it's easy to miss applying the header on any particular resource, so the EPR:1 should be sticky.  I've updated section 4.3 of the spec to call this out, and specify that EPR:0 is the way to effectively turn off EPR for a given origin.
