### ISSUE TITLE
CREDENTIAL: Reconsider the top-level browsing context limitation.

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec#380]
Step 3.2 of https://w3c.github.io/webappsec/specs/credentialmanagement/#request-credential rejects the Promise returned by `get()` if it's called from a nested browsing context. @hillbrad suggested that this limitation would be a problem; I argued with him a bit on the last call (http://www.w3.org/2015/05/18-webappsec-minutes.html#item01), but now I think he might be right.

I'd suggest changing the text to prevent returning credentials _without user mediation_ in a nested browsing context, but allowing the user to choose to grant access to credentials in a nested context. @hillbrad's argument that this actually increases security (for all the reasons that the API/password managers in general increase security in the top-level frame) seem reasonable.

I am still a bit worried about confusing the user with a popup that refers to a frame inside the document they're looking at, but I'm working on convincing myself that it's fesiable.

/cc @devd, @terriko, @dveditz who also participated in the discussion.

**Comment by hillbrad** [comment]
Thanks, Mike.  It think requiring user mediation is a good safeguard here.

**Comment by terriko** [comment]
The more I think about this, the more I think we should really do some usability research on this front, at least at the level of "buy a user a beer and get them to tell us if this is totally confusing" repeated a few times before it gets encoded into a standard, because it's pretty clear that what's confusing to us and what's confusing to other users is going to be pretty different.  I'll do a quick trawl through some usable security papers and see if this is obviously a bad (or good) interface, too.

**Comment by mikewest** [comment]
CCing @adrifelt, who has both opinions about security UX and permissions/requests from iframes.

**Comment by adrifelt** [comment]
I agree with the concerns stated here: iframes are confusing to people, and it may not be clear who the request for credentials is coming from.

I'm somewhat confused though. When will credentials every be supplied without user interaction?

**Comment by mikewest** [comment]
> I'm somewhat confused though. When will credentials every be supplied without user interaction?

Assume something like the mock in https://w3c.github.io/webappsec/specs/credentialmanagement/#user-mediated-selection, which gives a user the ability to automagically log into a website if they choose to do so.

**Comment by adrifelt** [comment]
@mikewest Raymes Khoury and Ben Wells are going to do a usability study on the topic of iframes and user expectations. This might be worth mentioning to them. I have no good answers for what users expect w/r/t iframes so I'm really glad they're planning to look into this.

**Comment by mikewest** [comment]
Punting this for the moment, as the status of permission requests in frames is somewhat up in the air.

@hillbrad, would this block Facebook from implementing?

**Comment by hillbrad** [comment]
Just to be clear - you're not changing the requirement that the promise for
get() be rejected in anything but a top-level browsing context.

I don't know that this would particularly block Facebook, but I know it
would greatly decrease the usefulness of the features to someone like
PayPal, which uses in-context iframes for checkout and has short-lived
sessions.   I see that pop-up dialogs are problematic in embedded contexts,
but still feel that for origin-bound credentials this should be safe,
modulo some UI redress scenarios that can and should be addressed by
X-Frame-Options or CSP frame-ancestors.

Is the form auto-filler disabled for iframes?

**Comment by mikewest** [comment]
My thought here is that it's easy to add functionality if we discover that
we need it, but taking it away is hard.

I'd like to get a minimal version of this shipping in Chrome so we can
begin iterating on the implementation based on experience rather than
guesswork. *shrug*

It may well be that the initial feedback is "I can't use this because
frames!"  In which case, we should revisit this big for v1. :)

I suspect the bigger chunk of complaints will be around the HTTPS
requirements, though. That's what I'm hearing today (though I'm not
inclined towards budging on it :) ).

**Comment by mikewest** [comment]
This issue was moved to w3c/webappsec-credential-management#3
