### ISSUE TITLE
SRI: should integrity checks be restricted to 200 responses?

### ISSUE THREAD

**Issue by fmarier** [w3c/webappsec#384]
On https://lists.w3.org/Archives/Public/public-webappsec/2015May/0029.html, @manger suggested this:

> A better way to do this would be to say a resource is not eligible for integrity validation if it is returned with a 401 (Unauthorized) or 407 (Proxy authentication required) status.
>
> In fact, perhaps any response without a 2xx status should be ineligible; or restrict it to only 200 (Ok) responses."

**Comment by devd** [comment]
Longer term, a 40x in an iframe will still run, right?

**Comment by devd** [comment]
does "not eligible" mean it will fail the check? then I am fine with this.

**Comment by fmarier** [comment]
As per the algorithm in [Section 3.3.5](https://w3c.github.io/webappsec/specs/subresourceintegrity/#does-resource-match-metadatalist), a non-eligible resource with a non-empty integrity metadata will be blocked.

**Comment by devd** [comment]
aah yes, you are right. I am fine with blocking and failing. Although, per the fetch integration, won't it error out earlier (similar to CORS check not succeeding in a CORS fetch)

**Comment by devd** [comment]
@metromoxie does this just fall through because of the Fetch integration?

**Comment by metromoxie** [comment]
Why would it error out? I believe it would perform an HTTP Fetch (https://fetch.spec.whatwg.org/#concept-http-fetch), and if the response is a 401/407, it would do another HTTP Fetch with the credentials obtained and respond with the response from that second HTTP Fetch.

**Comment by devd** [comment]
actually, thinking a bit more. Since we have removed all the bits about authentication headers etc: it is just a CORS request, I think we don't need to treat 40x any different. If it is an actual error page, it will face the SRI check. And longer term, in the iframe case, it might be reasonable for a the integrity metadata to say: "this hash or the error page hash"

**Comment by metromoxie** [comment]
Yeah, that was my basic thinking. I think the CORS part is the real key. If the CORS headers say you can inspect the content... then it doesn't matter if it's a hash or a just reading raw data.

**Comment by devd** [comment]
lets close this then as no changes needed?
