### ISSUE TITLE
CSP: Refused to execute inline script even with a valid sha1 or sha256

### ISSUE THREAD

**Issue by WebReflection** [w3c/webappsec#400]
This page used to work (meaning no warnings should happen):
http://webreflection.github.io/DOMContentLoaded/example.html

Now it shows in console this on Opera:
![screenshot from 2015-06-12 16-18-46](https://cloud.githubusercontent.com/assets/85749/8132038/1703cca2-111f-11e5-87fb-5f16e95fc78b.png)

and it shows this on GNOME Web:
![screenshot from 2015-06-12 16-20-28](https://cloud.githubusercontent.com/assets/85749/8132046/22b23214-111f-11e5-9119-a09fe8346162.png)

Should I file a bug to these browsers or there's actually something wrong in the following layout I don't know? Thank you.

``` html
<!DOCTYPE html>
<html>
  <head>
    <title>DOMContentLoaded via CSP</title>
    <meta http-equiv="Content-Security-Policy" content="script-src 'unsafe-inline' 'self' 'sha1-//cbZaIlYySeh0GGSwpZKzOAkvg=' 'sha256-XpSHSiwcWV9TTNd43i/nMFtZA8u8gQVfVXEy6Wa68a0='">
    <script>(function(g,a,b,d){function l(m,c){var e={type:d,currentTarget:a,target:a},f=c||m;try{"function"===typeof f?f.call(a,e):f.handleEvent(e)}catch(b){g(n,0,b)}}function n(a,c){throw c||a;}function h(){a.removeEventListener(d,h);a[b]=function(b,c,e){b===d?g(l,0,c):k.call(a,b,c,!!e)}}var k=a[b];k.call(a,d,h)})(this.setImmediate||setTimeout,document,"addEventListener","DOMContentLoaded");</script>
  </head>
</html>
```

**Comment by mathiasbynens** [comment]
I don’t see anything in the console when loading that page in Opera v30.0.1835.52 (i.e. the latest stable release).

**Comment by WebReflection** [comment]
I am on 30 too, but on Linux

![screenshot from 2015-06-12 16-59-14](https://cloud.githubusercontent.com/assets/85749/8132793/7a41488a-1124-11e5-9642-2dc7219d2da3.png)

**Comment by mathiasbynens** [comment]
Interesting! I’ve filed this internally as DNA-39812.

**Comment by WebReflection** [comment]
right ... not sure when but this looks fixed now. ( it's github issues cleanup time :tada: )
