### ISSUE TITLE
Define a term that should guard access to "Powerful New Features"

### ISSUE THREAD

**Issue by jyasskin** [w3c/webappsec#41]
Along the lines of http://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features. There may need to be a pair of terms to cover before-load and after-load like "a priori insecure origin" vs "insecure origin".

This is related to slightlyoff/ServiceWorker#385, but I'm filing it here so I can update https://github.com/jyasskin/web-bluetooth when it's done.

**Comment by mikewest** [comment]
We've moved this discussion to https://w3c.github.io/webappsec/specs/powerfulfeatures/. Closing out this bug.
