### ISSUE TITLE
Mixed Content: fetch() in service workers broken

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec#415]
Per https://lists.w3.org/Archives/Public/public-webappsec/2015Jul/0055.html it seems this integration is broken.

**Comment by annevk** [comment]
Note that Mixed Content probably needs to depend on the new dialog window concept too: https://github.com/whatwg/fetch/issues/70 Only when there's a dialog window associated with the request do we actually want to allow mixed content.

**Comment by mikewest** [comment]
What is a "dialog window"?

**Comment by annevk** [comment]
The visible window associated with the request. Perhaps "dialog" is the wrong term if we also want to use this here. "User-interface window" might be more appropriate.

**Comment by annevk** [comment]
We stopped caring about mixed content in service workers afaik.
