### ISSUE TITLE
Ambitious charter timeline

### ISSUE THREAD

**Issue by jonathanKingston** [w3c/webappsec#421]
Is it worth republishing the charter timeline on the group homepage?

http://www.w3.org/2015/03/webappsec-charter-2015.html

Clearly some of those deadlines have already not been met and might be better to publish a timeline (I got asked when SRI might become a recommendation for example)

**Comment by dveditz** [comment]
This seems like a question for the mailing list, not a github issue with a specific spec.

**Comment by jonathanKingston** [comment]
@dveditz yup my bad sorry will raise now. Thanks
