### ISSUE TITLE
SRI: stable references to Fetch

### ISSUE THREAD

**Issue by fmarier** [w3c/webappsec#428]
Given that Fetch is a living standard, how should we ensure that Section 3.4 of SRI (which will be frozen once published) continues to make sense?

Right now, it refers to specific steps and section numbers, which I assume could change at anytime.

/cc @annevk

**Comment by annevk** [comment]
I think the plan is to simply fold 3.4 into Fetch so you can remove it.

I noticed btw that you also patch `Request`. Was it intended to also support this for `fetch()`?

**Comment by annevk** [comment]
The "match" link also seems broken.

**Comment by annevk** [comment]
I learned from @metromoxie that `fetch()` indeed needs to work. It seems all is set for integration then.

**Comment by annevk** [comment]
I did notice that the current `Request` constructor modifications don't account for mode being "no-cors". That should probably result in an exception.

**Comment by annevk** [comment]
We also probably do not want `integrity = ""` as that would remove integrity checking when you pass a request through a service worker. I'll fix this and the above when integrating.

**Comment by annevk** [comment]
Alright, integrity support has now landed in Fetch per the issue referenced before. I suggest that you folks remove your "Modifications to Fetch" section and reference Fetch as appropriate for "integrity metadata".

**Comment by metromoxie** [comment]
Great, thanks @annevk. I'll update it next week.

**Comment by fmarier** [comment]
> Alright, integrity support has now landed in Fetch per the issue referenced before. I suggest that you folks remove your "Modifications to Fetch" section

Done in #460.

> and reference Fetch as appropriate for "integrity metadata".

Do you have a specific place in mind for this? A new one-line section that just says that Fetch is appropriate for this?

**Comment by annevk** [comment]
Well, whenever you talk about the request's integrity metadata, you want to reference https://fetch.spec.whatwg.org/#concept-request-integrity-metadata, no?
