### ISSUE TITLE
CLEAR: grammar nit

### ISSUE THREAD

**Issue by mozfreddyb** [w3c/webappsec#429]
1.1.2: `Megacorp’s CEO, however, once lost hours and hours of progress in "Irate Ibix" due to inadvertant site-data clearing, and so is refuses to allow such a sweeping impact to the site’s users.`
Last part should be `and so refuses to`. Omit the `is`.

cc @mikewest

**Comment by mikewest** [comment]
PR!

**Comment by mozfreddyb** [comment]
on a friday afternoon? sigh…

**Comment by mikewest** [comment]
(also, while you're there, it should be "Ibexes")
