### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by tyoshino** [w3c/webappsec#434]
In the "5.3. Should response to request be blocked as mixed content?" section ( https://w3c.github.io/webappsec/specs/mixedcontent/#should-block-response ),

In the note at the top,

> (e.g. because the response is a blockable request,

This should be 

> (e.g. because the response is a blockable response,

I think. Or "resource" instead of "response"? It seems optionally-blockable and blockable are defined only for resource and request.

----

This commit ( https://github.com/w3c/webappsec/commit/e577d4d5746bd33248a7dd4dbe0db515c16f20fb ) removed "not" from 

>  if <var>context</var> is not an <a>optionally-blockable request context</a>, return <strong>blocked</strong>.

Is this intentional? Current algorithm blocks optionally-blockable but allows blockable.

----

The step 7 of "5.2. Should fetching request be blocked as mixed content?" algorithm should end with else case. I.e. one more substep should be added as 7-7 which returns **allowed**.

----

In the "7.5. Service Workers" section ( https://w3c.github.io/webappsec/specs/mixedcontent/#service-workers ),

> to launder optionally-blockable requests into blockable responses

Is this written as intended? Don't you mean that we should disallow laundering blockable into optionally-blockable?

**Comment by mikewest** [comment]
Thanks!

> In the note at the top,
> > (e.g. because the response is a blockable request,
>
> This should be
>
> > (e.g. because the response is a blockable response,
>
> I think. Or "resource" instead of "response"? It seems optionally-blockable and blockable are defined only for resource and request.

Yes. Changing to "because the request is blockable..."

> > if context is not an optionally-blockable request context, return blocked.
>
> Is this intentional? Current algorithm blocks optionally-blockable but allows blockable.

Ugh. Yes, I meant to change this to "is a blockable requerst context". I got halfway there! :)

> The step 7 of "5.2. Should fetching request be blocked as mixed content?" algorithm should end with else case.

I've just changed step 8 to return `allowed`. Should have done that to begin with... thanks!

> > to launder optionally-blockable requests into blockable responses
>
> Is this written as intended? Don't you mean that we should disallow laundering blockable into optionally-blockable?

It was quite poorly phrased, thanks: I'll replace it with "... launder responses to optionally-blockable requests into responses to blockable requests."

**Comment by tyoshino** [comment]
> It was quite poorly phrased, thanks: I'll replace it with "... launder responses to optionally-blockable requests into responses to blockable requests."

Ah, now I understand what you meant! Thanks!
