### ISSUE TITLE
CREDENTIAL: requestAutocomplete can already provide local credentials

### ISSUE THREAD

**Issue by mnoorenberghe** [w3c/webappsec#445]
The LocallyStoredCredential aspect of the spec duplicates functionality provided by requestAutocomplete with autocomplete="(username/new-password/current-password)" and doesn't seem to be adding enough value to justify having duplicate UI. As an implementer of a password manager and requestAutocomplete, I don't want to have to maintain separate UI for these two specs as there is significant overlap and I believe the differences/inconsistency could confuse users.

I also think the user experience is much better building local credential support on top of requestAutocomplete (rAc) as it can fill complete forms with one button click and already has a good fallback story for browsers that don't support it where they simply show the <form> they already created. Browsers can already indicate if they can't support rAc for some fields in the form. Being able to complete a whole registration form (e.g. Name, Email, Address, Username, & Password) with one rAc dialog would be much better than having to use rAc followed/preceded by a separate credential management API call and UI.

I propose that the local credential support be specified atop the existing requestAutocomplete specification instead of a standalone spec. I haven't looked at the federated credential aspects recently to know if they could also be easily mapped into rAc but I suspect they could using new `autocomplete` values and `<input type="hidden">`.

**Comment by mikewest** [comment]
Interesting! This isn't something I'd thought about at all, thanks for bringing it up.

I agree that there's some conceptual overlap between the credential management API's support for passwords and `requestAutocomplete()`. That said, I think I disagree that the one can replace the other, given some of the properties that I'd like the credential management API to support. The big things that occur to me at the moment are:

1. The gesture requirement for `requestAutocomplete()` differs from the gesture requirements for the credential management API (https://w3c.github.io/webappsec/specs/credentialmanagement/#user-mediation-requirements). In particular, this would require some special-casing for the kinds of use cases outlined in that section.

2. `requestAutocomplete()` returns the password directly to the page's DOM, which leaves it accessible to JavaScript (and therefore XSS). Ideally, we wouldn't be forced to do that when signing into a site.

3. It's unclear to me how `requestAutocomplete()` would deal with some of the things we'd like to do in the future: FIDO interactions, for instance, are quite different than usernames and passwords, as are federated token generations, etc.

There are some aesthetic reasons to prefer something other than `rAC` as well. The event-driven interface (as opposed to Promises), for instance, but those aren't particularly important. The list above is more interesting for discussion.

**Comment by jonathanKingston** [comment]
Can I also mention it is my belief the Credentials Management API isn't coupled to there being a form at all?

For example I can visualise a day where the 'happy case' for users with a password manager is:

Signup:
- Click register
 - Site brokers a conversation with the password manager
 - Site async registers the user
- User is redirected to a "well done for registering"

Login:
- Click login
 - Site brokers a converstation with the password manager
 - Site async logs them in
- User is presented the control panel

**Comment by mikewest** [comment]
@jonathanKingston: I didn't mention that because I share @mnoorenberghe's fervent hope that developers will have a `<form>`-based fallback story. :)

But yes, I think the non-fallback scenarios you present are appealing. :)

**Comment by jonathanKingston** [comment]
@mikewest oh sure I agree fallbacks should always should happen unless perhaps its a browser only app.

I meant the 'happy case' is that a user never sees a form at all which this can be achieved with `requestAutocomplete` however it seems mostly coupled and likely to the same fields.

The advantage I see is that the 'happy case' can ask for the highest entropy key and potentially data that just wouldn't resemble a username and password. (I have some ideas about the key generation I will add to the other password generation issue soon)

**Comment by mnoorenberghe** [comment]
> The gesture requirement for requestAutocomplete() differs from the gesture requirements for the credential management API (https://w3c.github.io/webappsec/specs/credentialmanagement/#user-mediation-requirements). In particular, this would require some special-casing for the kinds of use cases outlined in that section.

I guess I'm looking for an incremental improvement over the status quo and not as worried about login without user mediation as a first increment. I do think that it's not that big of a deal to make the changes/special cases to the gesture requirements (perhaps depending on the data requested) if it means we can avoid having to duplicate similar functionality in separate APIs which would have to be implemented and maintained.

> requestAutocomplete() returns the password directly to the page's DOM, which leaves it accessible to JavaScript (and therefore XSS). Ideally, we wouldn't be forced to do that when signing into a site.

I thought that this spec also had an API which returned the plaintext password at one point but perhaps I'm mistaken or it was changed. I believe your write-only password field proposal addresses this issue and the spec could require that field is write-only, if desired.

> It's unclear to me how requestAutocomplete() would deal with some of the things we'd like to do in the future: FIDO interactions, for instance, are quite different than usernames and passwords, as are federated token generations, etc.

I don't know much about FIDO or other future plans but I'm assuming the inputs and outputs can be stringified and therefore can be read and written by rAc using something like `<input type=hidden autocomplete="some-new-autocomplete-token">`. See the `transaction-*` autocomplete tokens for examples of the page passing information to the rAc dialog.

@jonathanKingston, rAc doesn't require showing a form or fields to a user. As you imply, it's trivial to implement a library that could dynamically create invisible inputs for you to get the data. For your happy and "potentially data that just wouldn't resemble a username and password", as long as it can be stringified I think it would work fine with rAc.

**Comment by mikewest** [comment]
@mnoorenberghe: Thanks for following up!

One thing I forgot to mention in the previous response: the rAc proposal can only replace `get()`, right? What do you think about `store()`? I don't really see an analog for that.

> I guess I'm looking for an incremental improvement over the status quo and not as worried about login without user mediation as a first increment.

What use cases are you interested in solving? Registration of new accounts, or sign-in? It seems like rAc might be well-suited to the former, given that it can fill a number of field types at once, rather than being limited to usernames and passwords. I'm less enthused about it for the latter, for reasons I'll get to in a moment.

> I thought that this spec also had an API which returned the plaintext password at one point but perhaps I'm mistaken or it was changed.

It did (and I think Chrome's implementation currently does). We dropped that in the hopes of making it less likely that the password would leak in two ways:

1. The password isn't available to JavaScript via the Credential object. I think you're correct to say that the `write-only` concept could solve this.

2. The password can only be submitted to same-origin endpoints, and won't follow redirects while doing so. I suppose we could add more attributes to `<form>` in order to bring these qualities in as well. but that actually requires more developer effort. I'd like to make it hard for folks to screw this up, as it seems like 

3. The API only works in secure contexts. I don't actually remember whether rAc works over HTTP. I think Chrome's implementation doesn't, but I don't think that's a requirement in the spec (https://html.spec.whatwg.org/#dom-form-requestautocomplete).

>I believe your write-only password field proposal addresses this issue and the spec could require that field is write-only, if desired.

I would like to dig that up again, but note that this only solves the JavaScript access; malicious folks can submit `write-only` fields anywhere they like, which means it doesn't significantly reduce the risk of exfiltration.

> I don't know much about FIDO or other future plans but I'm assuming the inputs and outputs can be stringified 

I wish the FIDO folks would work out their patent issues so we could talk about a concrete proposal. As-is, I can only suggest that the workflows for these kinds of things are more interactive than I think rAc can easily enable. That is, you get an object back from `navigator.credentials.get({ 'fido': 'yes please' })` that then has a number of methods hanging off of it for assertion generation and signing. There's also a registration step that we'd model using `store()` (which, again, I forgot to mention as a concern in my initial response, apologies!).

/cc @annevk @AxelNennker @tanvihacks @sicking

**Comment by mikewest** [comment]
Ping.

**Comment by AxelNennker** [comment]
Sorry for the late reply. Holiday season.

I was quite excited when rAc was proposed at Google IO two years ago but then it kind of vanished.
https://www.youtube.com/watch?v=1M50AXPd0Tg

Does Google have some numbers on uptake? How many sites use rAc for CC information? How many sites use rAc for login?

Getting into the topic which web technologies succeed and which fail is a topic on its own. I guess this is bigger than this issue #445 and even bigger than webappsec.
Maybe the time was just not ripe for rAc? Is it now? Maybe the marketing for “use rAc for login” is/was non existing and with a little push from major companies it could be THE thing. I don’t know.

Coming back to this issue: I think that rAc could be used to fill username/password form-fields but browsers do that already. Why should sites use rAc for that then?
So the promise of credentialmanagement API is to pave the way for a time past username/password by making it attractive for sites to use the API. And THEN move forward to more secure options.

I think that a new API is better suited for this promise than rAc. It is true that we could tweak rAc to support federation and all but I feel this is hacky.

-Axel

There is a ton of failed attempts to solve Identity on the web:
Microsoft tried Information Cards in 2005.
There was a W3C Workshop on Identity in the Browser in 2011 http://www.w3.org/2011/identity-ws/report.html . Participants could only agree on that some crypto would be good to have and so WebCrypto was born.
I ;-) suggested a minimal javascript for openid. http://ignisvulpis.blogspot.de/2012/11/javascript-api-for-openid.html
BrowserID
WebID / FOAF+SSL
I thought then and still think that the browser should help users to manage their identities. But it is hard.

**Comment by mikewest** [comment]
This issue was moved to w3c/webappsec-credential-management#2
