### ISSUE TITLE
CSP: Deal with local schemes in new browsing contexts?

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec#451]
From https://lists.w3.org/Archives/Public/public-webappsec/2015Jul/0126.html:

> https://code.google.com/p/chromium/issues/detail?id=511824 notes that
`blob:` URLs can be popped up into new windows, bypassing the inheritance
structure that CSP sets up for IFrames. Though this seems consistent with
the spec and with other browser's behavior, it's probably something we
ought to change in CSP3.
>
> Any objections to pushing CSP from an opener window to an openee in the
same cases where we'd push CSP from a parent frame to a child frame (e.g.
when the URL is a globally unique identifier)?

**Comment by hillbrad** [comment]
Makes perfect sense to me.

**Comment by mikewest** [comment]
I believe that's the conclusion the thread reached as well. It'll happen in CSP3.

**Comment by mikewest** [comment]
This issue was moved to w3c/webappsec-csp#19
