### ISSUE TITLE
referrer source from (dedicated | shared) workers

### ISSUE THREAD

**Issue by yutakahirano** [w3c/webappsec#456]
Hi,

[The] (https://w3c.github.io/webappsec/specs/referrer-policy/) [spec] (https://w3c.github.io/webappsec/specs/referrer-policy/#determine-requests-referrer) says we should use referrer source when we are in a worker. The referrer source was specified when [running a worker] (https://html.spec.whatwg.org/multipage/workers.html#run-a-worker), and for dedicated worker, [it is the global object when creating the worker] (https://html.spec.whatwg.org/multipage/workers.html#dedicated-workers-and-the-worker-interface:run-a-worker). 
That means we should use the parent document's (stripped) url for the referrer source, is that correct?

Thanks,

**Comment by annevk** [comment]
No, you should use the URL of the worker itself. What the specification says is that when you fetch the worker itself, then you use the referrer source of the "parent". But only then.

**Comment by yutakahirano** [comment]
Thanks, but I'm still confused. I would like to know where I got it wrong.

> What the specification says is

Which spec do you mean?
I thought 

> If request’s referrer is a URL, then let referrerSource be request’s referrer. Otherwise:

section in the referrer policy spec should be used for "client" referrer.

**Comment by annevk** [comment]
I was talking about the worker specification.

See e.g., https://html.spec.whatwg.org/multipage/workers.html#dom-workerglobalscope-importscripts which says to use incumbent settings object as referrer source. That is the global object of the worker. Any other API that does network fetches in workers will be similar.

It's only the fetch for the worker itself that has this special referrer source, to avoid using the global object created for the worker.

**Comment by yutakahirano** [comment]
Ah, I think I understand.

Does that mean will the referrer source be passed to "determine request's Referrer" algorithm from the fetch algorithm in the future?

**Comment by annevk** [comment]
In the future the workers specification will be written in terms of Fetch and rather than passing Fetch a referrer source it will pass Fetch a referrer that is either a URL, "client", or "no-referrer".

**Comment by yutakahirano** [comment]
Thank you very much.
