### ISSUE TITLE
CSP: Evaluate a JSON syntax.

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec#457]
If we end up breaking backwards compatibility, perhaps we could change the header syntax entirely as well. See https://lists.w3.org/Archives/Public/public-webappsec/2015Aug/0077.html for a brief discusion of that concept, and https://gist.github.com/jonathanKingston/5699b440f608960dc089 for a syntax proposal.

**Comment by annevk** [comment]
What reason is there to break compatibility? So far this sounds an awful lot like XHTML 2.0.

**Comment by mikewest** [comment]
"If", right? I don't know of anything at the moment that would break compatibility with the existing syntax. In the absence of such a thing, we probably shouldn't introduce new header syntax.

*If* we end up needing such a thing, introducing a new header syntax would be an attractive way of managing the breakage and allowing for migration. Hence, this bug.

**Comment by mikewest** [comment]
This issue was moved to w3c/webappsec-csp#18
