### ISSUE TITLE
CSP: frame-ancestors grammar doesn't match what browsers implement

### ISSUE THREAD

**Issue by shekyan** [w3c/webappsec#461]
Grammar for frame-ancestors is:
```
ancestor-source-list = [ ancestor-source *( 1*WSP ancestor-source ) ] / "'none'"
```
while browsers allow 'self' as a ancestors-source-list, and I see many websites actually use
```
frame-ancestors 'self'
```
which doesn't comply with the specification.

**Comment by mikewest** [comment]
Yup, that's an oversight on my part. `'self'` is supposed to be an analog to `x-frame-options`'s `SAMEORIGIN`.

**Comment by shekyan** [comment]
Mike, I believe you meant adding 'self' to ancestor-source, and not to the ancestor-source-list, as you might want to combine 'self' with other ancestor-sources.

**Comment by mikewest** [comment]
*sigh* I did. Thanks for catching that.

**Comment by mikewest** [comment]
Fixed in https://github.com/w3c/webappsec/commit/54fea2a460b23ce42aa739ae6d77cb6d6d356aaf
