### ISSUE TITLE
CSP: Tests references in implementation report aren't in the repo.

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec#473]
Hey Brad! I don't see `http://w3c-test.org/content-security-policy/blink-contrib/self-doesnt-match-blob.sub.html` or `http://w3c-test.org/content-security-policy/blink-contrib/star-doesnt-match-blob.sub.html` in the w3c/web-platform-tests repo. Is there an outstanding PR I should take a look at?

**Comment by hillbrad** [comment]
Hrm.  I remember writing those, but they are indeed missing, and locally
for me as well.  I must've rage quit git and re-forked due to some
submodule nonsense about that time, and they were casualties.  Guess I'll
have to recreate them.  Thanks for the sharp eye.

**Comment by hillbrad** [comment]
Found them!  https://github.com/w3c/web-platform-tests/pull/2168
