### ISSUE TITLE
CSP: Consider an opt-in cascade model.

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec#474]
It would be nice if, like `<iframe sandbox>`, we had the ability to constrain the things that a subframe can do. We can't do that by default, as CSP is way too granular to safely apply on behalf of a potentially malicious embedder. It might be workable if the embedee opts-in, however (via CORS or some new mechanism). This could, for instance, be a contractually-enforced portion of an advertiser's deal.

Something to consider for CSP3.

**Comment by jonathanKingston** [comment]
I was waiting for me to complete the CSP JSON work to make this suggestion
but I was going to suggest a new extension to CORS which allowed further
restrictions from the outside in this manner so I'm very +1 for this
suggestion.

Something along the lines of:
    allow-access-control-restrictions: 1

And:
<iframe sandbox csp-restrictions="{scriptSrc: ['self']}" />

The problem this raised also is the use of " within an attribute there and
having to encode differently.

**Comment by hillbrad** [comment]
+1, I'm going to float some very broadly similar trial balloons at today
and tomorrow's W3C Digital Marketing workshop.

**Comment by mikewest** [comment]
@jonathanKingston: Yeah, something like that is what I was thinking. I don't think the JSON format is essential, however; we can just reuse the `<meta>` syntax.

@hillbrad: I am curious!

**Comment by deian** [comment]
+1 this would be great

**Comment by jonathanKingston** [comment]
@mikewest I 'think' the reason I was seeing the JSON format would be a prerequisite to this setup was around the issue of shared policies between frame content and site.

I'm not suggesting that sharing the policies solves the problem with automatic merging but setting restrictive CSPs would break the code too. I feel like the hardest part of this would be providing non normative advice for managing this process of CSP management between the two.

**Comment by briansmith** [comment]
Perhaps it could work like CORs. When the embedder sets restrictions, (the existence of) the restrictions would be passed to the embedee in an HTTP request header. If the embedee doesn't opt in to the restrictions via a CORS-like response header then the load just doesn't happen.

Maybe it could even be a CORs option?

**Comment by mikewest** [comment]
It might be worth considering an alternate approach: rather than forcing a policy on a document, perhaps we could allow the embedder to specify a policy, and abort the fetch if the headers of the loaded document don't contain a policy that's at least as restrictive? That wouldn't involve any modifications to CORS, or any new headers. The policy would also have the benefit of working in browsers that don't support this mechanism.

**Comment by briansmith** [comment]
That approach has a lot of appeal, but I think it will be too hard to compare one policy to another to verify that one subsumes the other.

However, I'd like to point out that such a subsumption comparison is more feasible as long as CSP remains a purely restrictive mechanism. In particular, the comparison seems like it would be difficult with the current design of CSP referrer but it would be easier with my proposed new design for CSP referrer.

**Comment by mikewest** [comment]
I'd agree both that subsumption will be complex (but certainly not impossible) to assert with regard to purely restrictive directives, and that directives which can loosen a page's security stance will be even more complex. I think both can be addressed, though, and I think I prefer the complexity of this approach to the complexity of the CORS-based approach.

In particular, I like that the page being loaded can agree to a _specific_ policy which the embedder can require, rather than agreeing to _any_ policy.

**Comment by jonathanKingston** [comment]
Yeah knew there was another reason, blocking on request based upon the
frames CSP is certainly far more attractive than managing multiple policies
(Devs likely will just copy and paste the latest policy where as suggesting
to an ad platform that they will likely not load when they are abusive is
better -  inconsistent breaking at execution time is also a risk with the
first design).

Would the iframe be able to block if no policy is specified too? Assuming
that doesn't create other risks.

The work I was mainly working around JSON CSP was mostly around deciding
how to merge policies (I was considering an API which node and browser can
pick up). So allowing the developer to merge policies and a method to test
if a policy subsumes another.

**Comment by mikewest** [comment]
Starting on a strawman proposal for this: https://mikewest.github.io/csp-embedded-enforcement/

It's all trivial except the subsumption work, which is hugely complicated (as @briansmith suggested). :)

**Comment by mikewest** [comment]
This issue was moved to w3c/webappsec-csp#12
