### ISSUE TITLE
CSP section 4.2.2 step 2 performs case sensitive test for url scheme

### ISSUE THREAD

**Issue by michaelficarra** [w3c/webappsec#475]
Schemes elsewhere in the CSP specification are treated case insensitively, but the wording here

> ... and url’s scheme is not one of `blob`, `data`, `filesystem`, then return *does match*.

suggests a case-sensitive comparison. I believe this is an oversight.

**Comment by hillbrad** [comment]
URL parsing implicitly normalizes the protocol portion to lowercase.

**Comment by michaelficarra** [comment]
Then the other comparisons should be made case sensitive for consistency.

**Comment by mikewest** [comment]
This issue was moved to w3c/webappsec-csp#11
