### ISSUE TITLE
CSP section 4.2.2 step 8 restricts loopback allowance to 127.0.0.1

### ISSUE THREAD

**Issue by michaelficarra** [w3c/webappsec#476]
Step 8 explicitly allows 127.0.0.1 as the only IP address that may be matched. I think this should be expanded to include all loopback addresses, which includes the range `127.0.0.0/8`.

**Comment by mikewest** [comment]
I think the intent was to restrict the scope of the carve-out for loopback addresses to the one that's used most (and actually appears in policies in the wild. See Facebook, for example).

**Comment by hillbrad** [comment]
(FYI: Facebook's policy only contained this to work around the Chrome on
iOS bug with the localhost implementation of the SafeBrowsing service for
mobile WebKit, so I would not consider it a canonical example of why we
need this carve-out.)

**Comment by michaelficarra** [comment]
What would be the reason to allow one but not any other loopback address?

**Comment by mikewest** [comment]
This issue was moved to w3c/webappsec-csp#10
