### ISSUE TITLE
CSP2: copy/paste bug in `default-src` definition.

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec#481]
> Let the default sources be the result of parsing the default-src directive’s value as a source list if a default-src directive is explicitly specified, and otherwise the U+002A ASTERISK character (*).

This is a copy/paste error on my part. A missing `default-src` should have no effect; as written, it would block inline script and eval.

**Comment by mikewest** [comment]
Not in CSP1, really just an error on my part: http://www.w3.org/TR/2012/CR-CSP-20121115/#default-src

@hillbrad / @wseltzer: Let me guess. We'll need to go back through CR to fix this?

**Comment by hillbrad** [comment]
I would say this is a correction that does not need a new feature, (indeed,
it specifies continuity of behavior with already specified behavior which
has gone through multiple exclusion periods) so perhaps we can get the
Director's approval to amend the CR without triggering an new exclusion
period?

**Comment by mikewest** [comment]
Actually, looking at this again, I don't think it has any impact. We're not "enforcing" the `default-src` directive if it's not present in the list of directives, so the value doesn't matter at all. Specifying that it's the `*` character makes no sense, but it's not actively harmful.

**Comment by mikewest** [comment]
This issue was moved to w3c/webappsec-csp#9
