### ISSUE TITLE
CSP: connect-src 'self' and websockets

### ISSUE THREAD

**Issue by klings** [w3c/webappsec#489]
Declaring a CSP with connect-src ‘self’ will not allow websockets back to the same host/port, since they're not same origin. This might come as a surprise to developers that haven't studied the CSP specification in detail and have a firm grasp of the same origin security model.

One option could be to add a note to the spec to clarify that this is the intended behaviour. Another option could be to make an exception for connect-src 'self', and allow ws(s): requests to same host/port.

I'm not sure what the security implications could be of the latter, but it might be worth some consideration.

**Comment by mikewest** [comment]
This issue was moved to w3c/webappsec-csp#7
