### ISSUE TITLE
CREDENTIAL: could we make it easier to extend?

### ISSUE THREAD

**Issue by jonathanKingston** [w3c/webappsec#490]
Hey all,

So I was taking a closer look at the [Credential Management API](https://w3c.github.io/webappsec/specs/credentialmanagement) and [CredentialRequestOptions](https://w3c.github.io/webappsec/specs/credentialmanagement/#interfaces-credentialrequestoptions) struck me as not very extensible.

Initial thoughts:
- Does CredentialRequestOptions make sense as an object, an array of typed objects may make sense
- Having a separate meta/options object may make more sense:
  - This allows for extension points like: https://github.com/w3c/webappsec/issues/250#issuecomment-136005063
  - `suppressUI` key doesn't fit with the other two keys
- Does having a two part interface to **Credential** make more sense for their API?
  - Constructor could be separated from a `create()` method.
    - FederatedCredential constructor would stay the same
    - PasswordCredential would move it's arguments to: `.create({id: 'myid', password: 'mypassword'})`

For example:
```
  navigator.credentials.get([
    new PasswordCredential(),
    new FederatedCredential({
       "providers": [ "https://identity.example.com/" ]
    })
  ], {
    suppressUI: true
  })
```

And:

```
  navigator.credentials.get([
    new PasswordCredential()
  ], {
    suppressUI: true,
    credentialClass: 2 
  })
```

Extensible methods:
- [Point 10 of request a credential](https://w3c.github.io/webappsec/specs/credentialmanagement/#request-credential) could be defined as a private method on **Credential** which could potentially be extended by method in future?
- [Point 6 of store a credential](https://w3c.github.io/webappsec/specs/credentialmanagement/#request-credential) this could be defined on **Credential** and the promises could also be too where each type extends rather than the switch in: https://w3c.github.io/webappsec/specs/credentialmanagement/#store-originboundcredential

**Comment by mikewest** [comment]
I don't think this is a good proposal, though I'm curious about the underlying critique.

1. I've structured the `get()` method to take an object which is used as a filter. The idea is that you have a bunch of credentials in the browser, and `get()` scopes down those credentials which the browser can offer up to the user for a decision. Passing credential objects into `get()` a) seems significantly more complicated, and b) doesn't make as much broad-strokes sense. What's the model it's representing?

2. I feel like the filter option to `get()` allows for substantial extensibility. That is, if you define a new credential type, you only need to add an item to the dictionary, and define the filters that that item can take. `FederatedCredential` defines `FederatedCredentialRequestOptions`, for instance.

3. `suppressUI` is _different_ than the other two options, but it's also a filter. That is, it's stripping out all credentials that can't be delivered without user mediation. The name continues to be bad, but I don't think it's wrong to be in the dictionary.

4. I don't understand the "two-part interface to `Credential`" bit of your suggestion. Could you explain?

**Comment by jonathanKingston** [comment]
> I don't think this is a good proposal, though I'm curious about the underlying critique.

Sure I'm certain I am not right however my goal is to reduce the confusion with the algorithms and where the types begin. Ideally minting a new type should be a case of the group agreeing on a type and the separate spec could cover this new credential type.
My goal somewhat is to remove the need for: [Extension implementation](https://w3c.github.io/webappsec/specs/credentialmanagement/#implementation-extension)


1. The idea of providing credential objects allows for:
 - providing class instances somewhat strikes me as better OOP design encapsulation where by the instances handle individual control of the resources they require, many instances could be provided and keys of mixed purposes are separated into the correct instances.
 - yes it is more complex initially however depending on the number of type instances would also equally become as problematic

2. I'm not someone to get picky about OOP design however relying on a dictionary as the expansion point works, however this isn't like adding keys to an AJAX request where there is always one expected request format, it's more like making a factory increasingly complex over time. What I am asking for is something that looks perhaps more like an adapter pattern (I'm sorry for mentioning OOP buzzwords however it is the clearest way I can convey the API code smell here)

3. The key name isn't the issue here, the idea this belongs to multiple credential types seems wrong to me.

4. Certainly this wasn't clear. The more I have thought of this the more I think this might be clearer than my initial thoughts:

```
  navigator.credentials.get({
  "password": true,
  "federated": {
    "providers": [ "https://federation.com" ]
  }, {
    suppressUI: true
  })
```

Changes are:
- Overarching filters are separated from type specific options (This means less key collisions and keys directly map to types, as mentioned suppressUI may be one of many here)
- All algorithms specific to the types then are handled by the type specific classes via methods or similar.
  - As mentioned in my first message storing and requesting: 4.1.1, 4.1.2, 4.2.3, 5.3.1
    - For example: 4.1.1 `Credential` could define a `associatedRequest()` method which would cover point 10. of the algo. Other new types could extend/override when changes were required.
  - Handling of [CredentialRequestOptions](https://w3c.github.io/webappsec/specs/credentialmanagement/#interfaces-credentialrequestoptions) becomes a method within specific classes. So the shape of `password` is defined as an interface within the class of `PasswordCredential`.
    - For example:
      - [3.2.1.1](https://w3c.github.io/webappsec/specs/credentialmanagement/#interfaces-credentialrequestoptions) would be left suitably vague that it would contain keys which would relate to the types, the types themselves would specify a key `requestOptions` which would specify the correct shape of the value here.
      - [3.2.1.2](https://w3c.github.io/webappsec/specs/credentialmanagement/#interfaces-federatedcredentialrequestoptions) would become a key on the `FederatedCredential` class perhaps: `requestOptions`

```
dictionary FederatedCredentialRequestOptions {
  sequence<USVString> providers;
  sequence<DOMString> protocols;
};

interface FederatedCredential : OriginBoundCredential {
  readonly attribute USVString provider;
  readonly attribute DOMString? protocol;
  FederatedCredentialRequestOptions requestOptions;

  static Promise<any> registerAsProvider(DOMString protocol);
};
```

Kind regards

**Comment by mikewest** [comment]
This issue was moved to w3c/webappsec-credential-management#1
