### ISSUE TITLE
CSP: clarify whitespace characters

### ISSUE THREAD

**Issue by michaelficarra** [w3c/webappsec#498]
See my comment in https://github.com/w3c/webappsec/issues/495#issuecomment-145291880.

> 4.2.1 separates source expressions on U+0020 (space), U+0009 (tab), U+000A (line feed), U+000C (form feed), and U+000D (carriage return), and the source-list grammar separates source expression on WSP, which is only U+0020 (space) and U+0009 (tab).

I think we should just replace usage of RFC 5234 `WSP` (the latter usage above) with HTML5's `space characters` (the former usage above).

**Comment by hillbrad** [comment]
As part of a HTTP header, though, we can't allow line feeds or carriage
returns.

**Comment by shekyan** [comment]
CSP spec should be transport agnostic and inputs containing LF and CR would be restricted by HTTP. Consider the case of meta-tag as a transport and HTML entity representing a new line.

**Comment by mikewest** [comment]
This issue was moved to w3c/webappsec-csp#5
