### ISSUE TITLE
CSP: Identify enforced or report only policy in JSON

### ISSUE THREAD

**Issue by ScottHelme** [w3c/webappsec#499]
When receiving a report from the UA there is no defined method to identify whether it was the result of an enforced policy or a report only policy. 

Is it possible to add a new key into the report JSON such as report-only:true when the UA received the policy in report only mode?

I've currently tackled this issue on the test site for https://report-uri.io by allowing the user to set a GET parameter in their policy reporting address which signals a report only policy. Whilst this works, it's not an ideal solution and depends upon the user to both set the value in the report only policy and then unset it when the policy is enforced. This has presented the opportunity for human error to cause inaccuracies in the categorisation of incoming reports. 

GET parameters can be used as a standard method of transmitting additional information along with the report, yes, but it seems that whether or not the policy was enforced should be something that the user isn't expected to communicate.

**Comment by hillbrad** [comment]
This has been discussed on list before (can't find the link right now).  So
far we have preferred to suggest use of GET parameters to encode things
that the server can know when setting the policy: whether the policy is
report-only or not, whether and which features are enabled (e.g. for sites
doing A/B testing) and the like, and restrict the report to things that are
known only by the client at enforcement time. GET query parameters are one
of the most fundamental building blocks of the web and we need to carefully
consider the cost and value of adding additional complexity to a spec when
roughly the same results can be achieved by simple composition of existing
abstractions.

**Comment by mikewest** [comment]
This issue was moved to w3c/webappsec-csp#4
