### ISSUE TITLE
CSP: Function called via [[Construct]] is the same as Function called via [[Call]]

### ISSUE THREAD

**Issue by michaelficarra** [w3c/webappsec#500]
In section 7.15, "allowed script sources" is defined for source lists *not* containing `'unsafe-eval'`. There appears to be an unnecessary qualifier, "When called as a constructor, ..." because, as ECMA-262 edition 6 states in [section 19.2.1](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-function-constructor),

> Thus the function call `Function(…)` is equivalent to the object creation expression `new Function(…)` with the same arguments.

**Comment by mikewest** [comment]
This issue was moved to w3c/webappsec-csp#3
