### ISSUE TITLE
CSP: make available a reliable method for obtaining a reference to the global object

### ISSUE THREAD

**Issue by michaelficarra** [w3c/webappsec#501]
At times, it is necessary to obtain a reference to the global object. In different environments, this object has non-standard, writable self-references: `global` in node, `window` in certain browser contexts, `self` in other browser contexts, etc. It is not a good practice to rely upon these references. For this reason, a particular pattern using the `Function` constructor is the only reliable method (of which I'm aware) for obtaining a reference to the global object in any context (strict/sloppy mode, module/script).

```js
var honestToGodGlobalObject = Function("return this")();
```

Because this is a use of the `Function` constructor, CSP does not allow this pattern without adding `'unsafe-eval'` to my policy. How can we make an exception to allow this pattern or something equivalent?

**Comment by hillbrad** [comment]
Is this an ECMAScript issue?

**Comment by michaelficarra** [comment]
It could be solved from the ECMAScript side, but there's [little hope of that happening](https://esdiscuss.org/topic/putting-global-reference-in-specs). All I ask is that this particular pattern (or the `(0, eval)("this")` equivalent mentioned in the linked thread) be allowed because of its uncontested utility.

**Comment by mikewest** [comment]
If JavaScript isn't giving you the thing you need in a consistent way, I think you'll need to poke at JavaScript to solve your problem. :( In fact, it's entirely possible that folks would use CSP specifically to prevent you from grabbing access to the global object as part of a larger sandboxing mechanism. I don't think there's much value in carving out loopholes.

More practically, I don't think there's a good way to distinguish "safe" usage of `Function` or `eval` from non-safe usage. What you want is a well-defined `global` reference, not a pile of hacks.

**Comment by mikewest** [comment]
This issue was moved to w3c/webappsec-csp#2

**Comment by shekyan** [comment]
This issue was moved to w3c/webappsec-csp#89
