### ISSUE TITLE
CSP: ECMA-262 does not define "operator eval"

### ISSUE THREAD

**Issue by shekyan** [w3c/webappsec#503]
Section 7.15 mentions operator `eval`
>If 'unsafe-eval' is not in allowed script sources:

>Instead of evaluating their arguments, both operator `eval` and function `eval` [ECMA-262] MUST throw an EvalError exception.

Operator `eval` is is not defined neither by ECMA-262, nor by the CSP specification.

**Comment by mikewest** [comment]
This issue was moved to w3c/webappsec-csp#1
