### ISSUE TITLE
[SRI] Shared Cache through `sharedcache` attribute

### ISSUE THREAD

**Issue by brillout** [w3c/webappsec#504]
The idea of using the digest defined in the `integrity` attribute as key for a cross-origin shared cache has been discussed before.
It seems that the idea has been rejected.
However I can't find the reason why it has been rejected.

Concretely, I don't see how following implementation would imply a security flaw.

Upon

```
<script src="https://cdn.example.org/common-library.js"
           integrity="sha384-+/M6kredJcxdsqkczBUjMLvqyHb1K/JThDXWsBVxMEeZHEaMKEOEct339VItX1zB"
           sharedcache="true"
           crossorigin="anonymous"></script>
```

following algorithm is applied;
1. If the shared cache holds an asset with the same digest as defined in the integrity attribute:
  -then: Load this asset from the shared cache instead of fetching the asset over the network. Don't apply step 2.
  -else: Apply step 2.
2. Upon successful loading of the asset and successful validation with the integrity attribute add the loaded asset to the shared cache.

Note 1: As per the SRI specification, the validation is only successful if `cdn.example.org` has set the CORS headers.

Note 2: If the `sharedcache` attribute is missing or set to false then do not apply the algorithm and proceed normally as defined in the current SRI specification.

Note 3: The author should be aware that adding the `sharedcache` attribute to an asset loaded exclusively on its website effectively exposes its website to a "history-tracking-attack"; any other website can check if the user visited the website by checking if the shared cache holds the exclusive asset. However, the `sharedcache` is meant to be used with common assets loaded by many websites which renders such attack not very useful (the attacker can at best know that the user has not visited a website, i.e. it is infeasible to get an exhaustive list of all websites loading a common asset).

How does this hold a security flaw that would justify the rejection of such feature?

This would turn SRI into not only a security feature but also a performance feature.
It would be super convenient to be able to use common JavaScript libraries and other web assets with almost no network cost.
Not only would this increase performance of the web but it would also allow new size-heavy libraries to emerge.

(I've sent a copy to the mailing list because the Call for Consensus requires so, feel free to close this issue if posting on the mailing list is enough)

**Comment by brillout** [comment]
As for CSP; scripts with `sharedcache="true"` should be treated equally as inline scripts.

Because
 - We should assume that an attacker is able to add arbitrary assets to the shared cache (e.g. via a website he owns)
 - Therefore setting the `integrity` attribute while `sharedcache="true"`, is equivalent to setting the content of the script to the source of the asset, i.e. is equivalent to inline scripting

**Comment by brillout** [comment]
As for a "history-tracking-attack"; Following mechanism would make it considerably more difficult to achieve such attack:

A new resource is added to the shared cache on a probabilistic base and based on how many domains reference the resource:
 1. For the first two visited domains that reference the resource, the resource is not added to the shared cache.
 2. For every subsequent visited domain that reference the resource, the resource is added to the shared cache with a probability of 30%.

**Comment by annevk** [comment]
Duplicating this against https://github.com/w3c/webappsec-subresource-integrity/issues/22.
