### ISSUE TITLE
Way to disown window.opener and become a secure context

### ISSUE THREAD

**Issue by jakearchibald** [w3c/webappsec#517]
Similar to https://github.com/w3c/webappsec/issues/139 but for _this_ window.

If `http://example.com` contains:

``` html
<h1>Check out thes cooool web appz:</h1>
<ul>
  <li><a href="https://jakearchibald.github.io/svgomg/" target="_blank">SVGOMG</a></li>
  …
</ul>
```

…and the user clicks on that link, I can't use geolocation because I'm not a secure context. It'd be nice to prevent that.

Unfortunately we'll need a different mechanism for service worker, which needs to be secure before handling the navigation fetch.

**Comment by delapuente** [comment]
I think you mean a link with `target="_blank"`. Does not it?

**Comment by jakearchibald** [comment]
Oops, yep. Updated.

**Comment by yoavweiss** [comment]
> Unfortunately we'll need a different mechanism for service worker, which needs to be secure before handling the navigation fetch.

Can we make that value "sticky" so that sites that declare it once (perhaps with a certain `max-age`) will have this property when opened later? That way sites can add this opener opt-out on the initial navigation, and SW would be able to use the same opt-out.

**Comment by yoavweiss** [comment]
At the same time, [auto-disowning opener](https://github.com/slightlyoff/ServiceWorker/issues/890#issuecomment-237260453) is probably a good idea on its own.

**Comment by annevk** [comment]
Superseded by https://github.com/whatwg/html/issues/4078 and https://github.com/whatwg/html/issues/3740.
