### ISSUE TITLE
CSP3: Provide a mechanism to override previous directives

### ISSUE THREAD

**Issue by jwatt** [w3c/webappsec#528]
https://w3c.github.io/webappsec-csp/#multiple-policies

says "The impact is that adding additional policies to the list of policies to enforce can only further restrict the capabilities of the protected resource."

The Content-Security-Policy HTTP header served by my site is fairly locked down by default, but sometimes I'd like to relax a directive for the odd page. For example, I have `frame-src 'self'` but would like to relax it for some pages. Rather than having to fiddle with .htaccess files and make sure that any .htaccess rules are moved along with the files they apply to if I move them to another location on the server, it would be more convenient to be able to use `meta` inline in the files to relax a restriction.

To avoid things being brittle in the face of files moving I'd imagine most people will just relax the CSP header the serve by default if they can't easily make ad hoc exceptions.

Allowing overrides from `meta` probably isn't safe for more most directives, or it's safety may depend on the value of other directives, or whether non-'self' script has been allowed to run before the `meta` tag is encountered. Or perhaps it's not safe for any directives, regardless? At any rate, it would either be good to have an override mechanism of some sort that works via `meta`, or else it would be good to have some text in the 'multiple policies' or 'meta' sections of the spec explaining why we can't have that.

**Comment by annevk** [comment]
Allowing resources to override restrictions stated in headers makes them vulnerable to injection attacks, unless you guard the `<meta>` elements through nonces somehow, but at that point you might as well use a different header (if you want to do it properly anyway).

**Comment by jwatt** [comment]
Would they still be vulnerable to injection attacks is no script has been encountered before the `meta` tag?

**Comment by jwatt** [comment]
Meh, you're talking about injection of the `<meta>` tag. Good point.
