### ISSUE TITLE
Content-Security-Policy didn't get into the IANA message header registry

### ISSUE THREAD

**Issue by jyasskin** [w3c/webappsec#532]
Even though https://www.w3.org/TR/CSP2/#iana-considerations says to add Content-Security-Policy and Content-Security-Policy-Report-Only to the permanent message header field registry, https://www.iana.org/assignments/message-headers/message-headers.xhtml doesn't include them. Did something fall down in the REC process?

**Comment by SmashManiac** [comment]
The registry has moved to [Hypertext Transfer Protocol (HTTP) Field Name Registry](https://www.iana.org/assignments/http-fields/http-fields.xhtml).

Can someone at the W3C take ownership of this? I don't think I can do the submission myself, and this issue has been pending for more than 4 years even though it should have been a trivial matter.

**Comment by mikewest** [comment]
Resolved in https://github.com/protocol-registries/http-fields/issues/14 and https://github.com/protocol-registries/http-fields/issues/15.
