### ISSUE TITLE
TPAC 2019 Agenda.

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec#555]
Suggestions or thoughts about [topics we should discuss at TPAC](https://github.com/w3c/webappsec/blob/master/meetings/2019/2019-09-TPAC-agenda.md)? This would be a lovely place to put them.

---

* Old Things
    * For the third year in a row, how do we get [Referrer Policy](https://www.w3.org/TR/referrer-policy/), [Secure Contexts](https://www.w3.org/TR/secure-contexts/), [Mixed Content](https://www.w3.org/TR/mixed-content/), and [Upgrade Insecure Requests](https://www.w3.org/TR/upgrade-insecure-requests/) to REC?
    * Ditto for [Clear-Site-Data](https://www.w3.org/TR/clear-site-data/), [Credential Management](https://www.w3.org/TR/credential-management/).
    * What are we doing with [Content Security Policy](https://www.w3.org/TR/csp/) and [Embedded Enforcement](https://www.w3.org/TR/csp-embedded-enforcement/)
    * ...
* Less-old Things
    * [Fetch Metadata](https://www.w3.org/TR/fetch-metadata/)
    * [Origin Policy](https://wicg.github.io/origin-policy/)
    * [CORS-RFC1918](https://wicg.github.io/cors-rfc1918/)
    * [Feature/Document/* Policy](https://www.w3.org/TR/feature-policy/) (@clelland?)
        * [Cookie Controls](https://github.com/w3c/webappsec-feature-policy/issues/85)
    * CORP/COEP/COOP + 👻 Spectre 👻
    * ...
* New Things
    * [Trusted Types](https://github.com/WICG/trusted-types) update. Adopt into the WG? ([@koto](https://github.com/koto))
    * HTTP State Tokens
    * Mixed Content 2 ([@estark37](https://github.com/estark37))
    * [`IsLoggedIn` API](https://lists.w3.org/Archives/Public/public-webappsec/2019Sep/0004.html) ([@johnwilander](https://github.com/johnwilander))
    * [CSP Next?](https://github.com/mikewest/csp-next)
    * Double-keyed (or more) caches
    * Protecting/sandboxing <iframe> sites (history.length, caches, window[i])
    * `Sec-Origin` (@deian)
    * ...
* Process Things
    * [Charter](https://www.w3.org/2019/03/webappsec-2019-charter.html) still reasonable?
        * Putting privacy more clearly in scope and make browser privacy policies part of the security review process
    * [Evergreen standards](https://www.w3.org/wiki/Evergreen_Standards)?
    * Relationship with other groups (TAG, PING, HTTPbis, etc.)
    * Security reviews of upcoming features.
    * Various browsers' launch processes

**Comment by annevk** [comment]
Ideas:
* Double-keyed (or more) caches
* Protecting/sandboxing `<iframe>` sites (`history.length`, caches, `window[i]`)
* Putting privacy more clearly in scope and make browser privacy policies part of the security review process

**Comment by mikewest** [comment]
@annevk: Added those in, thank you!

**Comment by deian** [comment]
Is there enough time to chat about a new Sec-Origin header we've been working on?

**Comment by Malvoz** [comment]
Too early to talk about [First-Party Sets](https://github.com/mikewest/first-party-sets)?

> Feature/Document/* Policy

I'm not sure how detailed discussions get at TPAC, but I'd like to highlight [Cookie controls](https://github.com/w3c/webappsec-feature-policy/issues/85), if I may.

> Protecting/sandboxing <iframe> sites (history.length, caches, window[i])

As a developer [I find sandboxing difficult](https://github.com/WebWeWant/webwewant.fyi/blob/master/wants/16.md). Either I'll restrict essential features due to lack of documentation from service providers, or take the safe route and restrict a very minimal set of features (or not use `sandbox` at all). Document-Policy might make things easier, but ultimately I think code distributors need a motivator to provide documentation on which features can be safely restricted without breaking the frame.

**Comment by mikewest** [comment]
@deian:
> Is there enough time to briefly chat about a new Sec-Origin header we've been working on?

Added it to the list. Will you be attending in person, or do we need to find a California-friendly time for you to dial in? Also, is there an explainer document we could link to so folks are up to speed on the proposal when we discuss it?

@malvoz:
> I'm not sure how detailed discussions get at TPAC, but I'd like to highlight Cookie control, if I may.

Added.

> As a developer I find sandboxing difficult.

I think it's generally the case that a frame-to-be-sandboxed needs to cooperate with its sandboxer if breakage is to be avoided. Just applying unexpected restrictions is unlikely to be effective, as you note. What do you think this group can do to improve that situation? Where would you like the conversation at TPAC to focus?

**Comment by wjmaclean** [comment]
Can we discuss an Origin Policy for opting in to Origin Isolation? We will have an explainer we can share before the end of this week.

**Comment by clelland** [comment]
Re: https://github.com/w3c/webappsec/issues/555#issuecomment-529440924, there have been a number of different proposals for isolating documents from each other -- this proposal with origin policy, a couple of different feature policy features, 'domain' in sandbox, and probably a couple of other ideas around agent cluster isolation. I don't think it's spefically within the charter, but is a general discussion around that problems space in scope for this group?

**Comment by cyberphone** [comment]
Web2App access is a popular topic outside of the W3C:
https://lists.w3.org/Archives/Public/public-payments-wg/2019Sep/0000.html
People do all sorts of tricks to circumvent the limits of the Web.  Why not give them something that has a blessing? URL Handlers doesn't really cut it and Web extensions like featured in Chrome (desktop only) are downright horrible since they potentially open open any site for DOM access.

**Comment by hober** [comment]
I imagine this issue can be closed now. Is there any plan for WebAppSec to meet at TPAC 2020? I don't see the group listed on the [group schedule page](https://www.w3.org/2020/10/TPAC/group-schedule.html).
