### ISSUE TITLE
Where's the right repository for reporting an issue of the doc of w3.org?

### ISSUE THREAD

**Issue by moonformeli** [w3c/webappsec#562]
I've been reading CSS position documentation, and I've found typos.
[Here](https://www.w3.org/TR/css-position-3/#rel-pos) and [here](https://www.w3.org/TR/css-position-3/#sticky-pos).

> A relatively positioned box establishes a new a new containing block for absolutely positioned descendants.

> A stickily positioned box establishes a new a new containing block for absolutely positioned descendants, just as relative positioning does.

I think "a new a new" is a typo. Where should I report this?

**Comment by annevk** [comment]
https://github.com/w3c/csswg-drafts. You might also be able to supply them with a PR.

**Comment by moonformeli** [comment]
Thank you, I'll try to send a PR on this
