### ISSUE TITLE
editorial issues with 2021 draft charter

### ISSUE THREAD

**Issue by dveditz** [w3c/webappsec#573]
Comments on https://github.com/w3c/webappsec/blob/2021-charter/admin/drafts/2021-charter.md

**Success Criteria**
there's still a placeholder "[Will be replaced with template text]". Not sure what's intended to go there.

**Deliverables**
Is "Suborigins" still an active specification we're working on?
Is "Origin-Wide Policy" the correct spelling? The [spec itself](https://wicg.github.io/origin-policy/) has "Origin Policy" on it but maybe there's a newer editor draft somewhere else?

**Patent Policy**
The policy you link to has the date "15 September 2020", while the charter text says "(Version of 5 February 2004 updated 1 August 2017)". Can we change this to simply "(updated 15 September 2020)" or is there a legal/policy reason we need to reference all the versions the group has operated under?

cc @mikewest @samuelweiler

**Comment by samuelweiler** [comment]
Thank you Dan.  The placeholder is something I added; don't worry about it.  (Mike copied over some sections of the old charter that will be replaced with updated things from the template.)  Same with patent policy - that will be fixed when this is crammed into the template.

Origin-Wide: you're right.  Mike and I just didn't do much updating of the deliverables from the old charter (yet).  

Suborigins: @mikewest ?

**Comment by mikewest** [comment]
1. Suborigins is not a thing we're currently working on. Given infinite time, we should! But we're not.
2. "Origin Policy" is the current spelling, yes. But I don't think that's baked either. "Origin-Wide" is fine for the moment, as an expression of what it _is_ rather than what it's _called_. Either way.

**Comment by samuelweiler** [comment]
I've posted a draft charter that includes Suborigins (still).  Closing this issue; feel free to open more.
