### ISSUE TITLE
[charter] set milestones for Permissions Policy, Permissions API, and Cred Man

### ISSUE THREAD

**Issue by samuelweiler** [w3c/webappsec#586]
@dontcallmedom suggests that we set milestones for these not-yet-at-CR specs to reach CR, in part because we have many other specs that depend on them.

* Permissions API: 29 specs depends on it
  https://w3c.github.io/webref/ed/#permissions
* Permissions Policy: 26 specs
  https://w3c.github.io/webref/ed/#permissions-policy
* Credential Management: 2 specs (incl a Rec)
  https://w3c.github.io/webref/ed/#credential-management-level-1

@mikewest & @dveditz, what would reasonable milestones for each of these be?

**Comment by plehegar** [comment]
cc @marcoscaceres

**Comment by marcoscaceres** [comment]
I'm happy to aim for mid-next year for CR for Permission API for mid 2022. There is some work to be done to integrate Permission Policy and Permissions API together.

**Comment by plehegar** [comment]
cc  @clelland and @equalsJeffH

**Comment by clelland** [comment]
I suspect that the integration @marcoscaceres mentioned will mean that we want to publish a version of Permissions Policy at around the same time as Permissions, so I'd like to aim for the same timeframe.

**Comment by equalsJeffH** [comment]
The timeframes being discussed in this thread sound nominally reasonable.
