### ISSUE TITLE
[charter] list Document Policy as a deliverable

### ISSUE THREAD

**Issue by samuelweiler** [w3c/webappsec#590]
@dontcallmedom suggests that we list [Document Policy ](https://wicg.github.io/document-policy/) as a deliverable.  

@dveditz @mikewest, opinions?

**Comment by annevk** [comment]
As noted in https://github.com/WICG/document-policy/issues/26 I have concerns about the name as I think we also want this for workers.

cc @clelland @jan-ivar

**Comment by clelland** [comment]
We navigated Feature -> Permissions Policy while the spec was under this group's charter, so I don't know if naming discussions should necessarily block this.
(I'm very supportive of having those discussions, and having them early. FWIW)

**Comment by samuelweiler** [comment]
Having seen little discussion here, I'm opting for the "no changes" approach.  It seems clear that this is in scope and can be adopted later.
