### ISSUE TITLE
Which process version is the WG using?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappsec#599]
Hi Chairs and @samuelweiler! I'm having some issues with auto-publishing the Permission spec. Echidna complain that the WG is not yet using Process 2020 (still using Process 2017?). 

Is that correct or we need to get the group information updated somewhere at the W3C?

**Comment by mikewest** [comment]
My understanding is that we're still using 2017, and that 2020 will come along with the charter refresh that's working its way through the AC and etc.

**Comment by marcoscaceres** [comment]
Yikes, ok... I updated the Bikeshed templates incorrectly then :( Will switch them to 2017 and we can revert once we are on 2020. 

Um, nothing to see here 😅

**Comment by wseltzer** [comment]
@mikewest, @marcoscaceres  the Patent Policy doesn't update until re-charter, but Process should be updated automatically when W3C adopts an update.

**Comment by marcoscaceres** [comment]
Ok cool. So, question: should I bother reverting the changes I made to Bikeshed? or do we expect the updates to happen quickly enough that this won't be an issue (e.g., in a week or two or are we looking at "months")?

**Comment by wseltzer** [comment]
The charter renewal is under discussion now, to see if we can resolve formal objections, so I'd expect ~month.

**Comment by marcoscaceres** [comment]
Ok, cool. Process 2021 might also be accepted by then. Will it be possible to have a lightweight transition path from 2020->2021 once we get charter approval?

**Comment by wseltzer** [comment]
As with Process 2020, I expect Process 2021 will be an automatic transition once approved by the AC and Director. The WG doesn't need to do anything but update documents.

**Comment by marcoscaceres** [comment]
That's great to hear. @wseltzer, sorry for my ignorance, but I'm guessing that "automatic transition" wasn't part of Process 2017. Is that why the group didn't transition automatically to Process 2020 already?

**Comment by wseltzer** [comment]
All groups and documents should have moved automatically to Process 2020 when it became operational 15 September, 2020. https://lists.w3.org/Archives/Member/chairs/2020JulSep/0076.html

Blame the team contacts (including me) if that didn't happen.

**Comment by marcoscaceres** [comment]
oh, ok! I see what happened now. The group was on the 2017 PP, which was not on track to be automatically updated with the new Patent Policy. That would require a recharter, as per the email above.

I'll update the Bikeshed templates.
