### ISSUE TITLE
[MIX] private origin does not account for IPv6

### ISSUE THREAD

**Issue by tomrittervg** [w3c/webappsec#60]
Section 2.1 lists the IPv4 private address space, but not IPv6.  I think RFC 4193 defines this for IPv6, but my notes indicate the following address spaces should probably be investigated as they may be security relevant:

    # IPv4 addressed Encoded into IPv6, where the IPv4 component is an RFC1918 address
    0::  ffff:AABB:CCDD - IPv4 Mapped Address (SIIT).  Also 0::ffff:aa.bb.cc.dd
    0::  0000:AABB:CCDD - IPv4 Compatible Address (SIIT). Also 0::0:aa.bb.cc.dd
    0::ffff:0:AABB:CCDD - IPv4 Translated Address (SIIT).
    2002:AABB.CCDD:: - 6to4 address. Send to the IPv4 Address AA.BB.CC.DD
    
    #Private Address Space
    fc??::  - Possibly, eventually, the local network 10.0.0.0/8 for IPv6.  Currently Reserved.  (Part of fc00::/7)
    fd??::  - The local network, 10.0.0.0/8 for IPv6.  Not routable unless conifgured explictly. (Part of fc00::/7)
    fe80::  - Space for Link Local Addresses (not all assigned \/ )
    fe80:0:0:0:: - Link Local Addresses. 169.254.0.0/16.
    fe80::0200:5efe:aabb:ccdd - ISATAP globally unique IPv4 translated address
    fe80::0000:5efe:aabb:ccdd - ISATAP private IPv4 translated address
    fec?:: - First attempt at 10.0.0.0/8 for IPv6, Deprecated. (Part of fec0::/10)
    fed?:: - First attempt at 10.0.0.0/8 for IPv6, Deprecated. (Part of fec0::/10)
    fef?:: - First attempt at 10.0.0.0/8 for IPv6, Deprecated. (Part of fec0::/10)
    
    #Multicast Addresses
    ffx?:: - Multicast Addresses - http://www.iana.org/assignments/ipv6-multicast-addresses/ipv6-multicast-addresses.xml
    ffx1:: - Interface-Local. 127.0.0.1; Packets may not exit box, stay within loopback.
    ffx2:: - Link-Local. Packets may not be routed anywhere, but may be passed within a subnet.
    ff02:0:0:0:0:1:ff??:: - Solicited Node Multicast Addresses
    ffx3:: - IPv4 Local Scope?
    ffx4:: - Admin Local Scope. Smallest scope an admin would need to configure. Kind of like two subnets.
    ffx5:: - Site-Local. Restricted to local physical network.
    ffx8:: - Organization-Local. Multicast within an organization. Not valid on public internet.
    ffxe:: - Global Multicast addresses
    ff3?:: - Unicode-Prefix-Based Multicast https://tools.ietf.org/html/rfc3306

**Comment by mikewest** [comment]
We've dropped the public/private distinction from the current draft of MIX, so this ends up being a question we don't need to answer.

Thanks for the report, regardless! Much appreciated. (And apologies that it took so long for me to get to it. :( )
