### ISSUE TITLE
Stop advising to people use the mailing list

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webappsec#602]
The Bikeshed templates still ask people to sign up to mailing lists. Everyone is using TikTok nowadays (jokes)... but seriously, we should encourage people to file issues at the appropriate Github repos instead.

**Comment by Seirdy** [comment]
The Web is an open platform, and shouldn't require signing up on closed platforms to participate. Perhaps an alternative to mailing lists is something the community wants, but I don't like the idea of steering everyone away from open and federated platforms and towards proprietary solutions.

Perhaps both options could be presented side-by-side?

**Comment by marcoscaceres** [comment]
Yep, side by side is nice. Don't get me wrong, I still use the mailing list for things, but I live here (at the W3C). I can imagine it would be super off putting for anyone who is not a W3C native.

**Comment by plehegar** [comment]
Unless someone points to a specific spec from webappsec that only encourages to use mailing lists, it's not clear what action remains to be done here. It may well be that one of those specifications just need to be republished with the latest templates. All of our specifications are in GitHub repositories nowadays and it has been a significant improvement from the past. W3C tracked around 1800 GitHub repositories nowadays. If a better alternative comes up, we can always consider it (and, please, consider the cost of maintenance when making a proposal).

**Comment by plehegar** [comment]
closing for now but feel free to reopen if there is new information.
