### ISSUE TITLE
Planning the 2023-03-15 call.

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec#618]
We ended up skipping the 2023-02-15 call due to lack of availability, and will pick back up on 2023-03-15 with the following sketch of an agenda:

*   Deprecations and defaults:
    *    @johnwilander's linked-on-or-after idea
    *    @tomvangoethem wrote up a [`Progressive-Security` header](https://secweb.work/presentations/2022/Goethem-deprecation.pdf) in a SecWeb presentation last year.
    *    @mikewest wrote up a [`Baseline` header](https://github.com/mikewest/baseline-header).
*   @heisenburger will [report](https://www.w3.org/Privacy/permissions-ws-2022/report) on the [Workshop on Permissions](https://www.w3.org/Privacy/permissions-ws-2022/)
*  @shhnjk wants to talk through https://github.com/w3c/FileAPI/issues/192.

/cc @dveditz

**Comment by mikewest** [comment]
Punted `/.well-known/change-password` as well as the following from January to February:

> * A few proposals in the same general area of deprecations and defaults have cropped up that might be worth discussing:
>   * @johnwilander floated a linked-on-or-after idea at TPAC (which he'd like to punt to the February meeting)
>   * @tomvangoethem wrote up a [`Progressive-Security` header](https://secweb.work/presentations/2022/Goethem-deprecation.pdf) in a SecWeb presentation last year.
>   * I wrote up a [`Baseline` header](https://github.com/mikewest/baseline-header).

**Comment by mikewest** [comment]
We're about two weeks out, so it's likely worth starting to solidify the upcoming call:

*   Deprecations and defaults:
    *    @johnwilander, will you be around and interested in talking through linked-on-or-after?
    *    Likewise, @tomvangoethem, will you be around to talk through `Progressive-Security`?
*   @hober and/or @rmondello: Would either of you be around to discuss moving https://www.w3.org/TR/change-password-url/ and https://w3c.github.io/webappsec-change-password-url/response-code-reliability.html along the path to REC?

I'd appreciate y'all's suggestions for additional topics you'd like to discuss.

**Comment by mikewest** [comment]
@heisenburger might be interested in talking about some of the conclusions from [December's workshop on permissions](https://www.w3.org/Privacy/permissions-ws-2022/).

**Comment by mikewest** [comment]
Friendly ping to... everyone on this thread. :)

**Comment by mikewest** [comment]
@heisenburger is on board to talk about the workshop on permissions' report.

@johnwilander and @tomvangoethem: Will y'all be around to talk about the various ideas floated above?

@hober and/or @rmondello: Will y'all be around to discuss moving your documents to REC?

Any other topics we should cover?

**Comment by johnwilander** [comment]
I have tried and failed thrice to have a WebKit internal meeting to get aligned on linked-on-or-after. Ppl have provided good input and references to past discussions but I need to get some key folks in a room. I may not make it before this call. :(

**Comment by mikewest** [comment]
Hrm. In that case, I think we'll punt on next week's meeting given that the only confirmed topic is the permissions workshop, and that's not pressing.

Can I lock you, @johnwilander and @tomvangoethem, in for next month's meeting? (And John, perhaps you could help me get in touch with @hober and/or @rmondello?)

**Comment by mikewest** [comment]
Shall we try again on the 15th at 9:00 PT? :)

@heisenburger will you be around to discuss the [workshop on permissions' report](https://www.w3.org/Privacy/permissions-ws-2022/report)?

@johnwilander and @tomvangoethem: Will y'all be around to talk about the various ideas floated above?

@hober and/or @rmondello: Will y'all be around to discuss moving your documents to REC?

**Comment by tomvangoethem** [comment]
I'm available on the 15th 👍

**Comment by shhnjk** [comment]
Hi @mikewest, if there is a space on the agenda for March 15th, I would like to present https://github.com/w3c/FileAPI/issues/192. WDYT?

**Comment by mikewest** [comment]
@tomvangoethem: Great!
@shhnjk: I think we can add that to the agenda, yes. Thanks!

**Comment by hober** [comment]
I can't make a meeting at that time on the 15th but I'll check with Ricky to see if they can!

**Comment by hober** [comment]
@rmondello can't make it either, I'm afraid.

**Comment by johnwilander** [comment]
I have had our internal meeting and can join on 3/15 at 9 am PT.

**Comment by mikewest** [comment]
Updated the agenda above accordingly. Thanks, all.

@hober and @rmondello: Understood, thanks for checking! I'll start a thread on the list, and see how far we get that way. :)

**Comment by mikewest** [comment]
Ugh. While pasting the agenda into https://github.com/w3c/webappsec/blob/main/meetings/2023/2023-03-15-agenda.md, I realized that next week is the daylight savings switch in America but not Europe.

I'm assuming that the W3C meeting scheduler is running in American time, which means that the meeting would be at 16:00 UTC, not 17:00 UTC (e.g. 16:00 London, 17:00 Berlin). Would that slot also work for you @tomvangoethem, @mozfreddyb, and @heisenburger?

/cc @dveditz and @plehegar to confirm my understanding of the schedule.

**Comment by mikewest** [comment]
Confirmed the timing, published the agenda on public-webappsec@ and https://github.com/w3c/webappsec/blob/main/meetings/2023/2023-03-15-agenda.md.
