### ISSUE TITLE
Planning the 2023-04-19.

### ISSUE THREAD

**Issue by mikewest** [w3c/webappsec#620]
Our next call is April 19th. We'll plan it here.

**Comment by mikewest** [comment]
Due to time constraints, we punted the discussion of https://github.com/mikewest/baseline-header to the next call.

**Comment by johannhof** [comment]
@dcthetall, @krgovind and I have been working on a [new proposal to converge browsers on semantics for blocking cross-site cookies](https://github.com/DCtheTall/standardizing-cross-site-cookie-semantics/), in the interest of solving security challenges that arise when cross-site cookies continue to be allowed by default in edge cases such as ABA (see more details in the document).

We'd like to present our findings and ideas to this group and discuss possible next steps. I'll also send out a small announcement to public-webappsec. :)

cc @arturjanc @annevk @johnwilander

**Comment by johannhof** [comment]
Forgot to cc Mozilla folks (@martinthomson @artines1 @mozfreddyb) who we would love to get feedback from ^

**Comment by mikewest** [comment]
@johannhof: This seems like something we can make time for. Though it will likely end up being specified as part of the cookie spec's "site for cookies" definition, it's clearly security-relevant, and worth discussing with folks in this group.

**Comment by mikewest** [comment]
Aiming to solidify the agenda with @dveditz tomorrow. Any additional topics come to folks' minds?

**Comment by bartoszniemczura** [comment]
If we find time, I'd like to circle back on discussions around Trusted Types we had about a [year ago](https://github.com/w3c/webappsec/blob/main/meetings/2022/2022-03-15-minutes.md#trusted-types-deployment-at-facebook-microsoft-and-google) (cc @shhnjk @koto) and discuss interest and potential paths for supporting Trusted Types across browsers.

**Comment by mikewest** [comment]
@bartoszniemczura SGTM.

I'm also inclined to continue punting the `baseline` header discussion, as there doesn't seem to be any immediate implementation interest. The other topics seem more pressing:

@dveditz, that would leave us with the following agenda:

*  @johannhof, et al would present https://github.com/DCtheTall/standardizing-cross-site-cookie-semantics/
* @bartoszniemczura, et al could discuss Trusted Types.

Does that work for you?
