### ISSUE TITLE
Planning the 2024-03-20 meeting

### ISSUE THREAD

**Issue by dveditz** [w3c/webappsec#643]
Planning the 2024-03-20 WebAppSec meeting. Please add potential topics below

**Comment by javifernandez** [comment]
I'd like to get feedback about this [PR](https://github.com/w3c/webcrypto/pull/362) to merge the Ed25519 and X25519 algorithms from the Secure Curves  Community Group Draft Report into the Web Cryptography API specification. 

In this [issue](https://github.com/WICG/webcrypto-secure-curves/issues/20) it's described the current implementation status.

**Comment by twiss** [comment]
I'd also like to discuss Curve25519 indeed, as well as a [proposal](https://twiss.github.io/webcrypto-modern-algos/) for other modern algorithms in Web Crypto, and feature detection (e.g. [`crypto.subtle.supports`](https://twiss.github.io/webcrypto-modern-algos/#partial-subtlecrypto-interface)).

**Comment by shhnjk** [comment]
I'd like to discuss about adding a reports for iframes into Permissions Policy: https://github.com/w3c/webappsec-permissions-policy/issues/537

**Comment by aaronshim** [comment]
I'd also like to continue the discussion on this [PR](https://github.com/w3c/webappsec/pull/639) around the WebAppSec Mitigations Wiki and where the most appropriate permanent home for this information might be.

**Comment by plehegar** [comment]
agenda+ TPAC 2024: webappsec meeting?

**Comment by plehegar** [comment]
agenda+ charter: https://github.com/w3c/webappsec/issues/645, https://github.com/w3c/webappsec/issues/646

**Comment by plehegar** [comment]
agenda+ Introducing @simoneonofri , new W3C Web Security Lead

**Comment by lukewarlow** [comment]
Could we add https://github.com/w3c/webappsec-csp/issues/651 to the agenda please, sorry it's a bit late.
