### ISSUE TITLE
Note for Standardizing Security Semantics of Cross-Site Cookies

### ISSUE THREAD

**Issue by DCtheTall** [w3c/webappsec#653]
Hey WebAppSec,

Last year we [discussed](https://github.com/w3c/webappsec/blob/main/meetings/2023/2023-04-19-minutes.md#cross-site-cookie-semantics) an effort to standardize differences we noticed between browsers' third-party cookie blocking mechanisms. We also discussed standardizing behavior for certain edge use cases for `SameSite=None` cookies.

@arturjanc and I have published a draft note [I am hosting](https://github.com/DCtheTall/webappsec-standardizing-security-semantics-of-cross-site-cookies/) we would like to publish as a WebAppSec note.

Thanks all in advance for your feedback!

**Comment by mikewest** [comment]
Thanks! Let's treat this as a CfC to publish this document as a [draft note](https://www.w3.org/policies/process/#draft-note), get a round of feedback or two and aim to call it done by TPAC? Next meeting is on the 17th. I think we can formalize publication at that point.

/cc @dveditz @simoneonofri

**Comment by mikewest** [comment]
Actually, I'm now wondering whether this would be a good fit for the new SWAG group that's spinning up: https://www.w3.org/community/swag/. WDYT about the WG NOTE vs CG Report dichotomy for something like this, @simoneonofri?

Same question could apply to https://www.w3.org/TR/post-spectre-webdev/, I think.

**Comment by simoneonofri** [comment]
hi @mikewest thank you for the pointer, talking with @torgo about that

**Comment by arturjanc** [comment]
My gut feeling is that while the notes seem similar to some extent (trying to unpack complex web platform behaviors related to the process model and cookies respectively), they're meant for fairly different audiences. The post-Spectre note is primarily geared towards web developers and tells them how to apply isolation protections for their services, whereas the cookie note is meant primarily for implementers / browser vendors to discuss the security trade-offs of different cookie-related behaviors. I.e. it's not particularly actionable for web developers as-is (but arguably useful to get some cross-vendor alignment in this space).

So I think WebAppSec might be a slightly better place for the cookie note conceptually, but I'm not at all opposed to SWAG if others have a preference for it.

**Comment by DCtheTall** [comment]
Hello all, given that when we presented this work at TPAC 2024 and the reaction was positive, I think it makes sense to move the draft note hosted at https://dcthetall.github.io/webappsec-standardizing-security-semantics-of-cross-site-cookies/ to the W3C org.

@simoneonofri would you be able to help us with that? Thank you :)

**Comment by simoneonofri** [comment]
hi @DCtheTall, from the GitHub side, if you can give me the permissions as the repository owner, I can transfer it (procedure here https://w3c.github.io/repo-transfer.html), and configure the w3c.json to link to the group

**Comment by DCtheTall** [comment]
Thanks Simone, I invited you to be a collaborator and will give you write permissions.

**Comment by simoneonofri** [comment]
@DCtheTall, thanks. I transferred the repository to w3c orga; now it is here: https://github.com/w3c/webappsec-standardizing-security-semantics-of-cross-site-cookies

**Comment by DCtheTall** [comment]
Thanks, @simoneonofri
