### ISSUE TITLE
SRI: noncanonical-src use cases

### ISSUE THREAD

**Issue by hillbrad** [w3c/webappsec#68]
"Issue-5" in the draft spec text states that noncanoncial-src only makes sense if we are allowing HTTP.  This is not true - it also allows for fallback in the case that e.g. a client is behind a proxy that intercepts and modifies HTTPS connections.  This is likely a nontrivial percentage of clients.  (e.g. enterprise and government systems)

**Comment by fmarier** [comment]
The `noncanonical-src` attribute was removed in 3629390e542a5bc181740f64c5e4d6d6bf4f053c.

**Comment by devd** [comment]
closing since we don't have noncanonical-src anymore
