### ISSUE TITLE
CSP Sec 5.1 Worker owner document clarification

### ISSUE THREAD

**Issue by deian** [w3c/webappsec#70]
We should update the first part to reflect the fact a blob/unique Worker inherits the CSP of the _owner document_ **or** _parent worker_ (if the parent worker has CSP header).  I am happy to provide a pull request if you agree with these semantics.

**Comment by mikewest** [comment]
Sorry, I forgot about this entirely. :/ Closed it in https://github.com/w3c/webappsec/commit/50cd0920cfba1a7d7b84659862eb24a44b4ca459.
