### ISSUE TITLE
[SRI]: use the terms of (un)authenticated origins instead of (in)secure channels?

### ISSUE THREAD

**Issue by mozfreddyb** [w3c/webappsec#71]
SRI currently uses and clarifies the terms *secure channel* and *insecure channel* in 2.1 (key concepts and terminology).

Do we instead prefer to talk about authenticated and unauthenticated origins, as we do in MIX?

**Comment by devd** [comment]
maybe just say "\S 5.1 from https://w3c.github.io/webappsec/specs/powerfulfeatures/#settings-privileged should return privileged"?

**Comment by mozfreddyb** [comment]
Sounds good.
Can we rely on this bit not to change, @mikewest? :-)

**Comment by mikewest** [comment]
As long as we stick with "privileged contexts", yes. But who knows if we'll stick with that. Perhaps y'all should comment on the thread. :)

**Comment by mikewest** [comment]
That said, I don't think you're using them for anything other than the authoring consideration section. You can probably drop the references altogether if you like.
