### ISSUE TITLE
SHA256 mismatches

### ISSUE THREAD

**Issue by kravietz** [w3c/webappsec#82]
Current working draft for CSP has the following test vector (Example 6):

    For example, the SHA-256 digest of alert('Hello, world.'); is qznLcsROx4GACP2dm0UCKCzCG+HiZ1guq6ZZDob/Tng=.

Calculated by the following command:

    echo -n "alert('Hello, world');" | openssl dgst -sha256 -binary | openssl enc -base64

I've tried that on two different machines (Mac & Linux) and the resulting hash is different:

    $ echo -n "alert('Hello, world');" | openssl dgst -sha256 -binary | openssl enc -base64
    b+jOy0DlwBaNGMxhuGypbGgvtY9mVoy1LlMALqJWsoY=

Just after that, there's another example that contains yet another hash, which is way too long for SHA256:

    Content-Security-Policy: script-src 'sha256-YWIzOWNiNzJjNDRlYzc4MTgwMDhmZDlkOWI0NTAyMjgyY2MyMWJlMWUyNjc1ODJlYWJhNjU5MGU4NmZmNGU3OAo='

**Comment by mikewest** [comment]
Sorry this took so long to fix. I missed a '.' in the bash command, and the example below should be SHA-512. Oops!

Thanks for catching both mistakes.
